### ISSUE TITLE
Add To Cart Only Works After Second Try

### ISSUE THREAD

**Issue by sprankhub** [nexcess/magento-turpentine#1027]
First of all, thanks for the extension and all your work! I am using version 0.6.7 with Magento 1.9.2.2 and a SSL wrapper.

I had an issue with a slightly modified rwd child theme. The problem was that the add to cart action on the product page did not work on first hit. There was no error or success message, the page simply reloaded. When I then hit add to cart again, it worked properly. The top mini cart was updated and I saw the success message.
I checked other issues handling empty cart problems. If I understood correctly, the issues should be resolved with the latest version. The "Use VCL fix" configuration setting was enabled. Changing it to disabled, so that the observer method is used, solved the problem. Is this the expected behaviour or shouldn't it work in both cases?

**Comment by miguelbalparda** [comment]
So far we found different scenarios and different fixes. If you disable the VCL fix the observer approach will be used inserting the form_key. There is another way documented here https://github.com/nexcess/magento-turpentine/pull/846#issuecomment-120626541

**Comment by sprankhub** [comment]
Thanks! But shouldn't both config settings Enabled/Disabled solve this issue, just in another way?

**Comment by miguelbalparda** [comment]
Both being enabled might collide between each other. 

If you enable the VCL Fix the first request will be piped to get a valid form_key and if you use the observer approach you will not be piped. While this should work every time we have seen several installations where only one fix works. 

Both fixes do work on a blank Magento install and most of the times having one fix not working is caused because  of a different theme or module interfering with Turpentine.

**Comment by npearson72** [comment]
FYI, I did a clean install with Magento CE 1.9.2.4 using the default rwd theme and sample data and only the VCL fix disabled seems to work :-(

**Comment by aricwatson** [comment]
@npearson72 can you give steps to reproduce? Perhaps try the same steps on our [demo site](http://turpentine-master.devsupport.nexcess.net/).
