### ISSUE TITLE
HTTPS in Unsecure Base URL Works for me

### ISSUE THREAD

**Issue by sprankhub** [nexcess/magento-turpentine#1029]
The [wiki](https://github.com/nexcess/magento-turpentine/wiki/SSL_Support) says that "using HTTPS in the unsecure base URL will not work". However, this works perfectly fine for me with Varnish 3.0.2. Not sure if I am the only one or this issue is not present any more... You may want to update the wiki.

**Comment by miguelbalparda** [comment]
We have been working towards a more uniform Varnish + SSL way, but with different results. How is your setup?

**Comment by sprankhub** [comment]
To be honest, I am not really sure :D The shop is running on Maxcluster, which provides some sort of SSL wrapper out of the box.

Just wanted to bring that up to discussion, so that other people can try it, give their feedback and you may be able to update the docs in the end.

**Comment by ADDISON74** [comment]
For more than half a year I am testing unsecure base URL with https protocol. When you're visiting frontend https is set by default, there is no need to redirect, rewrite conditions. Varnish/Turpentine combination is not creating any trouble. For production I am using unsecure with http, but giving secure for account access and checkout process.

My set up is Pound (80, 443) + Varnish (dev Turpentine) + Apache + Magento 1.9.2.2 with sample.

**Comment by arosenhagen** [comment]
we're using this in production with varnish4 for over a year now with fully enabled SSL on all pages (secure base URL == unsecure base URL) with no problems. Setup is nginx:80/:443 <-> varnish:6081 <-> nginx:8080

**Comment by ADDISON74** [comment]
From Turpentine Wiki: "Using HTTPS in the unsecure base URL will not work, Magento will get stuck in a redirect loop because of an issue (see https://www.varnish-cache.org/trac/ticket/1333). At least, this fix is not available for varnish 3".

If Pound is set up in front of Varnish pay attention to <strong>RewriteLocation</strong> directive and set it to 0 in ListenHTTP. I wrote a few posts into here related to my challenges with Pound/Varnish configuration. I do recommend using Pound in front of Varnish for both ports 80 and 443. It is so easy to control your communication flow from Pound configuration if you want skip Varnish service sometimes. Just change port numbers in Pound from Varnish to Apache/Nginx. You can also connect secure connections directly Pound to Apache is something bad is happening using Varnish. In conclusion you get more flexibility with Pound in front of Varnish.
