### ISSUE TITLE
Question: Crawler IP Address

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1043]
Here is my test configuration in a virtual machine:

Pound (IP_EXT, 80 and 443) => Varnish (127.0.0.1, 8090) => Apache (IP_EXT, 8080)

By default Crawler IP Address is set to 127.0.0.1. In the above scenario do I have to add Pound or Apache IPs in the list too?

**Comment by aricwatson** [comment]
I believe you'd want to leave the field blank in this scenario, but certainly be sure to test! See [this](https://github.com/nexcess/magento-turpentine/issues/596) for more info.

**Comment by ADDISON74** [comment]
I will test different scenarios. Now I am using 127.0.0.1, IP_EXT. I will report if the visitors share the same sessions. If there are other things to be watched please let me know.

PS - Could be this crawler IP Address set up a possible solution for famous ___SID=U issue? What do you think? I am doing SSL Offloading with Pound and ___SID=U means a session unsecured inserted in URLs.

**Comment by ADDISON74** [comment]
Update: I got <strong>crawler-session</strong> in frontend cookie in the above scenario. This is not good. I will test your suggestion with field left blank.

An important observation, if I get crawler-session value in frontend cookie, ___SID=U issue is not appearing at all. Very strange. Could we reverse Turpentine behavior to solve that issue based on this observation?

**Comment by ADDISON74** [comment]
@aricwatson Please check my latest post in #909 . You will be very surprised what I found playing with a crawler-session.

**Comment by ADDISON74** [comment]
@aricwatson Could you please let me know why if I set up my computer IP address as "Crawler IP" value in the list, visiting the webserver I do not get crawler-session cookie? But if I set up Crawler IP to server IP address I get crawler-session cookie. Is this a bug in Turpentine?

**Comment by aricwatson** [comment]
Sorry for the late reply, been busy as usual!

Here's the VCL that's actually generated from the Crawler IP and the Crawler User-Agents settings:

```
if (req.http.Cookie !~ "frontend=" && !req.http.X-Varnish-Esi-Method) {
	if (client.ip ~ crawler_acl || req.http.User-Agent ~ "^(?:ApacheBench/.*|.*Googlebot.*|JoeDog/.*Siege.*|magespeedtest\.com|Nexcessnet_Turpentine/.*)$") {
		set req.http.Cookie = "frontend=crawler-session";
	}
...
}
```

So, what that means is that the VCL *first* checks if the request does *not* include a frontend cookie and is not an ESI request. Then, it checks if the IP is in the list of crawler IPs or if it matches the User Agent list, and sets the crawler-session cookie in that case.

In your scenario, even though your IP in in the crawler list, all your requests will include a frontend cookie if you're browsing the site normally - which is why you don't get the cookie.

>  But if I set up "Crawler IP" value to webserver IP address I get crawler-session cookie. Is this a bug in Turpentine?

I haven't been able to replicate this behavior.
