### ISSUE TITLE
Best way to define page cache TTL?

### ISSUE THREAD

**Issue by Desmaster** [nexcess/magento-turpentine#1076]
I've been messing around with the page cache for a few hours and I'm a bit confused now.

**Why doesn't this cache my pages for 2 hours:**
![default_ttl](https://cloud.githubusercontent.com/assets/1165302/12419445/74590c7e-beb6-11e5-9af4-9e98d07144a1.PNG)

**And this does?**
![urlbased_ttls](https://cloud.githubusercontent.com/assets/1165302/12419457/846bae6e-beb6-11e5-8e4a-bd7eb7110123.PNG)

The fact that the second configuration works, **is obvious**. But why doesn't the default `ttl` seem to do anything? Or in other words, in what circumstances **does** Turpentine use the default page cache `ttl`?

**Comment by miguelbalparda** [comment]
Defalt TTL is being used but the name is different. See esi_private_ttl and https://github.com/nexcess/magento-turpentine/blob/6ffc75169f63f3fda7d2f1196b341e0db498064d/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php#L979 pulling the data fro that particular field.

**Comment by aricwatson** [comment]
If you have Turpentine set to pass the first hit to Magento to get a proper session ([Use VCL Fix](https://github.com/nexcess/magento-turpentine/wiki/Configuration) in config) - then subroutine that uses the default TTL (`generate_session_expires `) isn't used. That's probably why you're not seeing an effect, it's only used as the expiration for the cookie that's generated.

**Comment by Desmaster** [comment]
@miguelbarparda I can't agree with you, because the getter `getDefaultEsiTtl` simply returns `web/cookie/cookie_lifetime`.

**Comment by miguelbalparda** [comment]
Right @Desmaster my bad.

**Comment by Desmaster** [comment]
@aricwatson Are you sure you're not referring to `esi_private_ttl`? Because that's what your answer sounds like. 

If so, this issue remains unanswered. If not, van you clarify why you'd call cookie expiration time "Default Page TTL"? 

I'm not trying to bitch around here but some things seem really unlogical.

**Comment by miguelbalparda** [comment]
We encourage users to tell us what is wrong. We will review this issue and add it to our backlog to release a solution but If you think there is something that can be done in a different way you can also submit a pull request to speed the process.

**Comment by Desmaster** [comment]
@miguelbalparda I will look into submitting a pull request to make the cookie expiration time less confusing.

@aricwatson Can you let me know what you think?

**Comment by aricwatson** [comment]
@Desmaster I apologize, I was mistaken. It doesn't appear that the default TTL setting in Turpentine is actually used to set this value anywhere. It's set to be used in the VCL templates as `default_ttl` - however this is not actually used in any of the templates.

This is misleading however, because the value does get end up being used when the template variable called `{{url_ttls}}` is generated. That happens [here](https://github.com/nexcess/magento-turpentine/blob/80f97ce4f6aedec5c7b927572a9358e2c09fb280/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php#L299).

That basically reads the URL-based TTLs list, and if nothing is specified in there, it'll use the `default_ttl` value:

I verified this on the test server by downloading the generated VCL - and at the bottom of `vcl_fetch` the ttl is set:


    } else {
        set beresp.ttl = 3600s;
    }


Sorry for all the confusion!
