### ISSUE TITLE
pipe vs pass

### ISSUE THREAD

**Issue by andrewkett** [nexcess/magento-turpentine#1129]
I have been seeing some quite slow HTTP POST requests. It obviously makes sense that they are a bit slower as POSTs aren't varnished, but they seem to be significantly slower than they were before I setup varnish. 

I did a bit of playing around and found that changing 

```
   if (!true || req.http.Authorization ||
        req.method !~ "^(GET|HEAD|OPTIONS)$" ||
        req.http.Cookie ~ "varnish_bypass=1") {
        return (pipe);
    }
```

to

```
   if (!true || req.http.Authorization ||
        req.method !~ "^(GET|HEAD|OPTIONS)$" ||
        req.http.Cookie ~ "varnish_bypass=1") {
        return (pass);
    }
```

made the requests significantly faster. I have done a bit of reading but I will be honest, I still don't understand fully what pipe does or why it would be used over pass. pass on the otherhand seems pretty simple in comparison. Just wondering, is there a significant reason why pipe is used on such requests? I am considering returning a pass in my custom vcl include but I want to be clear why it was done in the first place and if I am going to break other things by doing it.

**Comment by aricwatson** [comment]
I can't comment on why pipe was originally chosen, but from my research it doesn't seem to be a necessity. Can you create a PR with this change so we can all test it? I suspect it's a good idea!

**Comment by andrewkett** [comment]
Hi @aricwatson I have created the pull request. Not sure if you meant only for non GET requests only or other instances of pipe. For now given my limited understanding of pipe I have only included the single line that I changed.

I did notice in the code there is a comment, "we pipe this instead of passing below because switching stores doesn't redirect (302), just acts like a link to another page (200) so the Set-Cookie header would be removed". Not sure if the same issue would apply to POSTs or not.

If it helps an example of a slow page I was seeing using pipe is the customer login action.

**Comment by johnnywalker** [comment]
I've been seeing this as well. After digging around, I believe this is related to https://www.varnish-cache.org/trac/ticket/1806

**Comment by digitalwert-developer** [comment]
As for what pass and pipe do: [http://www.varnish-cache.org/docs/3.0/tutorial/vcl.html#actions](http://www.varnish-cache.org/docs/3.0/tutorial/vcl.html#actions)

If I understand this correctly, "pipe" is meant to be a shortcut and varnish will act as a proxy only and will not modify the response - whereas with "pass", varnish is still able to do so.

---

I just ran into an issue regarding "pass" and "pipe".

Short story: When disabling the turpentine magento page cache, every request will be handled as "pass" (see [here](https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl#L127)).
However, requests to the magento backend should be handled using "pipe", because "pass" results in varnish removing all cookies.

If the turpentine magento page cache is enabled, the current implementation already uses "pipe", see [here](https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/misc/version-4.vcl#L152).

**Comment by Nuranto** [comment]
Strange thing : 
In current repo, version-4.vcl is using "return (pass);" when version-3.vcl is using "return (pipe);"...
Is there a specific reason to use pass for version 4 ?

**Comment by miguelbalparda** [comment]
@Nuranto I already did the change in devel, can you check if that is what you are saying?

**Comment by Nuranto** [comment]
Yes, it is fixed in devel indeed! My bad.

**Comment by miguelbalparda** [comment]
I'll close this for now, feel free to reopen it.
