### ISSUE TITLE
Crawler/cache warmer behaviour

### ISSUE THREAD

**Issue by R0n1n-77** [nexcess/magento-turpentine#1143]
Hi,
I noticed that both default crawler and warm-cache script do not work for me with Normalize User-Agent enabled.
To be more precise, they both hit pages, but when I browse to a crawled page I get "X-Varnish-Hits 0".
When I disable the Normalize User-Agent all works as expected and I get a right number of X-Varnish-Hits with any browser or client.
Is this a right behaviour or did I configure something else wrong?

**Comment by fweb** [comment]
According to @aricwatson the warmer script uses Siege to access each URL once. Unfortunately @data-digger said the `X-Normalized-User-Agent` for Siege is "other" which means it does nothing for real users.

https://github.com/nexcess/magento-turpentine/issues/1009#issuecomment-155877443

I'm still waiting to figure out a way to make it work

**Comment by aricwatson** [comment]
Just an update on this after running into it recently - If you have *Normalize User-Agent* turned on, then a normalized user agent is added to the hash for each item stored in Varnish. That means that there are **seven** different options based on the user's browser - as seen [here](https://github.com/nexcess/magento-turpentine/blob/6ffc75169f63f3fda7d2f1196b341e0db498064d/app/code/community/Nexcessnet/Turpentine/Model/Varnish/Configurator/Abstract.php#L770).

As @fweb points out, because Siege operates under with it's own User-Agent, any pages it warms will end up in the "other" category.

Our recommendation is to turn *off* the *Normalize User-Agent* setting, in which case the warmer script is much more useful. The problem to be aware of is that in this case mobile and desktop browsers will have the same page in the page cache - so it's important do any special responsive work *browser-side* (i.e. javascript, media-queries in css) and *not* to rely on the User Agent for detecting if the browser is a mobile browser.

I think we'll probably update Turp to only have two "buckets" if User Agent normalization is turned on - mobile and everything else. I doubt many people need to have special items in the page cache specifically for Chrome/Firefox/etc these days.

**Comment by fweb** [comment]
> I think we'll probably update Turp to only have two "buckets" if User Agent normalization is turned on - mobile and everything else.
Yep, this is what we need.

> I doubt many people need to have special items in the page cache specifically for Chrome/Firefox/etc these days.
Agreed, edge case

So from here, the warm-script will be updated to have an option to run either Mobile or Desktop user-agent bucket? Or would it just run for both?

And, this is kinda dumb, but apparently Siege can update its useragent using the -A flag. I should've just had several versions of it setup for the main browsers.
http://linux.die.net/man/1/siege

**Comment by aricwatson** [comment]
Yeah, you can run Siege that way. 

To change the user agent normalization it should basically be a matter of changing to this:

```
if (req.http.User-Agent ~ "iP(?:hone|ad|od)|BlackBerry|Palm|Googlebot-Mobile|Mobile|mobile|mobi|Windows Mobile|Safari Mobile|Android|Opera (?:Mini|Mobi)") {
        set req.http.X-Normalized-User-Agent = "mobile";
    } else {
        set req.http.X-Normalized-User-Agent = "other";
    }
```

Then run siege twice, once with a UA that matches the mobile, and then once with one that does not.

But I haven't had chance to test this yet.

**Comment by aricwatson** [comment]
I've added a PR that condenses the User-Agent normalization "buckets" into just "mobile" and "other" - https://github.com/nexcess/magento-turpentine/pull/1226
