### ISSUE TITLE
Duplicated frontend cookies

### ISSUE THREAD

**Issue by augpaschal** [nexcess/magento-turpentine#1153]
Hello

if the turpentine/varnish is enabled, then entering a page I see that the frontend cookie has domain www.example.com while the rest of the cookies have domain .www.example.com . 

Then when I go to the account page, another frontend cookie with domain .www.example.com  is generated and  the client can't connect to the account. 

If erase www.example.com cookie then i  can connect.

If turpentine is disabled (bypass varnish) then create cookie .www.example.com (same with each other e.g adminhtml) and the customer can connect..

Can you please help me?

**Comment by magenx** [comment]
#1075

**Comment by gewaechshaus** [comment]
https://github.com/nexcess/magento-turpentine/issues/1180

This definitly needs a fix...

**Comment by miguelbalparda** [comment]
@gewaechshaus why are you commenting on several issues referencing other issues? Can you be more specific please?

**Comment by gewaechshaus** [comment]
Yeah, for sure, was just collecting sources.  Stripped down: the version-3.vcl needs the same update like v4 in this PR https://github.com/nexcess/magento-turpentine/pull/1078, so somebody has to create a new PR

https://github.com/nexcess/magento-turpentine/issues/1180
You'll find the reason here...

**Comment by gewaechshaus** [comment]
@miguelbalparda - just created the PR https://github.com/nexcess/magento-turpentine/pull/1182
