### ISSUE TITLE
Using turpentine/varnish 3 with server-side A/B testing

### ISSUE THREAD

**Issue by otherjustin** [nexcess/magento-turpentine#1159]
Hi,
First, thanks for the great extension. We really love it.

A semi-short question about A/B testing: I'm making an issue for this because I imagine that it must have come up for many others, so I am hoping the community can offer some guidance: 
Are you aware of any documentation for using Varnish/Turpentine with server-side A/B testing, or can you offer advice for how best to get that working? We're using a an implementation of [ABLincoln](https://github.com/vimeo/ABLincoln) to basically swap out the template used by a block depending on the testing version the client should receive.

It seems like what would basically need to happen is for Turpentine to be aware of the tests being conducted, as I guess there would need to be some kind of hole-punch policy for the block being tested (a header change, in our case), as well as provision made for the cookie being set for the test within the VCL itself. I'm rather worried about the performance implications of the former especially, so I am hoping that there's already a battle-tested solution out there.

I really appreciate any help!

Thanks, otherjustin

**Comment by aricwatson** [comment]
One idea - actually have two headers on the page - however, hide/show the appropriate header with javascript/css. That way Varnish can just cache both headers in one ESI block.

That said - it might "just work" - since typically the header is set as a *private* block, so that each user has their own "version" cached in Varnish and pulled in via ESI. Let us know!

**Comment by aricwatson** [comment]
@otherjustin Please let us know if you found a good solution, I'm sure others would be interested!
