### ISSUE TITLE
Should we define varnish_bypass cookie name in backend?

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1166]
Question: Is it a good idea to define in backend the cookie name we want to use for skipping Varnish? I checked a lot of websites and using varnish_bypass cookie worked for all. Could this be a security issue?

**Comment by aricwatson** [comment]
I've been debating this for a long time. I suppose it *does* make DOS attacks slightly easier, since you can bypass Varnish - but there's tons of other ways to do this. For example, sending a ton of requests with no cookie would all get passed to Magento for a valid session (bypassing Varnish). Or using TLS. Or just spamming random paths in the request - which aren't unlikely to be in the Varnish cache. etc.

And it's handy to be able to use the Varnish bypass cookie when debugging Varnish issues. So it's not a change that seems likely to be hugely valuable, and does have downsides... 

I'm curious what other people thing?

**Comment by aricwatson** [comment]
I'm not sure this warrants the added complexity/time to implement. We're happy to reconsider if other's have good reasons for it!
