### ISSUE TITLE
Fix The Turpentine Cache Warmer

### ISSUE THREAD

**Issue by clwells** [nexcess/magento-turpentine#1207]
We need to update the cache warmer (and default bots UA regex).  The current warmer could be simplified in terms of the actual Siege call (and some Siege clients may not even match our default whitelist regex).  But more importantly the warmer needs to be adjusted to work with (or have better documentation about) clustered environments.

Depending on the environment the warmer may need to run on each node that Varnish lives (if using a distributed Varnish setup).

Further improvements would be prioritizing URLs in either a specialized sitemap and/or a generated list so that pages that are more prominent are cached first.

**Comment by fweb** [comment]
:+1: :+1: 

I wish it could just work with `X-Normalized-User-Agent`! I've been lurking for months, if not a whole year, for a solution.

Right now I manually run Screaming Frog with various user agents...

**Comment by aricwatson** [comment]
The problem is that `X-Normalized-User-Agent` is created based on the UA of the browser making the request...

I've just added a PR that helps somewhat with this, in that it condenses the User-Agent "buckets" down to just two groups - mobile and other: https://github.com/nexcess/magento-turpentine/pull/1226

**Comment by aricwatson** [comment]
I've updated the warming script to have more options - allow different UAs, etc - https://github.com/nexcess/magento-turpentine/pull/1243
