### ISSUE TITLE
New cache for every session issue

### ISSUE THREAD

**Issue by tagesjump** [nexcess/magento-turpentine#1253]
Peers hi
there is a problem
for each cookie it is caching new pages
so if i clear cookies in web browser, the first enter of page is also without cache

1) vcl is attached
2) using varnish3 and last version of extension
3) thinking that the problem is in  this

```

if (req.http.X-Varnish-Esi-Access == "private" &&
req.http.Cookie ~ "frontend=") {
hash_data(regsub(req.http.Cookie, "^.
*
?frontend=([^;]
*
);
*
.
*
$", "\1"));
}




C{
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <pthread.h>
static pthread_mutex_t lrand_mutex = PTHREAD_MUTEX_INITIALIZER;
void generate_uuid(char* buf) {
pthread_mutex_lock(&lrand_mutex);
long a = lrand48();
long b = lrand48();
long c = lrand48();
long d = lrand48();
pthread_mutex_unlock(&lrand_mutex);
sprintf(buf, "frontend=%08lx%04lx%04lx%04lx%04lx%08lx",
a,
b & 0xffff,
(b & ((long)0x0fff0000) >> 16) | 0x4000,
(c & 0x0fff) | 0x8000,
(c & (long)0xffff0000) >> 16,
d
);
return;
}
}C
import std;
include "dynamic_backends.vcl";
acl crawler_acl {
"127.0.0.1";
}
acl debug_acl {
}
/* -- REMOVED
sub generate_session {
if (req.url ~ ".*[&?]SID=([^&]+).*") {
set req.http.X-Varnish-Faked-Session = regsub(
req.url, ".*[&?]SID=([^&]+).*", "frontend=\1");
} else {
C{
char uuid_buf [50];
generate_uuid(uuid_buf);
VRT_SetHdr(sp, HDR_REQ,
"\030X-Varnish-Faked-Session:",
uuid_buf,
vrt_magic_string_end
);
}C
}
if (req.http.Cookie) {
std.collect(req.http.Cookie);
set req.http.Cookie = req.http.X-Varnish-Faked-Session +
"; " + req.http.Cookie;
} else {
set req.http.Cookie = req.http.X-Varnish-Faked-Session;
}
}
sub generate_session_expires {
C{
time_t now = time(NULL);
struct tm now_tm = *gmtime(&now);
now_tm.tm_sec += 3600;
mktime(&now_tm);
char date_buf [50];
strftime(date_buf, sizeof(date_buf)-1, "%a, %d-%b-%Y %H:%M:%S %Z", &now_tm);
VRT_SetHdr(sp, HDR_RESP,
"\031X-Varnish-Cookie-Expires:",
date_buf,
vrt_magic_string_end
);
}C
}
-- */
sub vcl_recv {
if (req.restarts == 0) {
if (req.http.X-Forwarded-For) {
set req.http.X-Forwarded-For =
req.http.X-Forwarded-For + ", " + client.ip;
} else {
set req.http.X-Forwarded-For = client.ip;
}
}
if(false) {
set req.http.X-Varnish-Origin-Url = req.url;
}
if (req.http.Accept-Encoding) {
if (req.http.Accept-Encoding ~ "gzip") {
set req.http.Accept-Encoding = "gzip";
} else if (req.http.Accept-Encoding ~ "deflate") {
set req.http.Accept-Encoding = "deflate";
} else {
unset req.http.Accept-Encoding;
}
}
if (!true || req.http.Authorization ||
req.request !~ "^(GET|HEAD|OPTIONS)$" ||
req.http.Cookie ~ "varnish_bypass=1") {
if (req.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?adm") {
set req.backend = admin;
}
return (pipe);
}
set req.url = regsuball(req.url, "([^:])//+", "\1/");
if (req.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?") {
set req.http.X-Turpentine-Secret-Handshake = "1";
if (req.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?adm") {
set req.backend = admin;
return (pipe);
}
if (req.http.Cookie ~ "\bcurrency=") {
set req.http.X-Varnish-Currency = regsub(
req.http.Cookie, ".*\bcurrency=([^;]*).*", "\1");
}
if (req.http.Cookie ~ "\bstore=") {
set req.http.X-Varnish-Store = regsub(
req.http.Cookie, ".*\bstore=([^;]*).*", "\1");
}
if (req.url ~ "/turpentine/esi/get(?:Block|FormKey)/") {
set req.http.X-Varnish-Esi-Method = regsub(
req.url, ".*/method/(\w+)/.*", "\1");
set req.http.X-Varnish-Esi-Access = regsub(
req.url, ".*/access/(\w+)/.*", "\1");
if (req.http.X-Varnish-Esi-Method == "esi" && req.esi_level == 0 &&
!(false || client.ip ~ debug_acl)) {
error 403 "External ESI requests are not allowed";
}
}
if (req.http.Cookie !~ "frontend=" && !req.http.X-Varnish-Esi-Method) {
if (client.ip ~ crawler_acl ||
req.http.User-Agent ~ "^(?:ApacheBench/.*|.*Googlebot.*|JoeDog/.*Siege.*|magespeedtest\.com|Nexcessnet_Turpentine/.*|SputnikBo/.*|Baiduspider/.*|YandexBot/.*|SemrushBot./*|Yahoo/.*|YandexMetrika/.*|DotBot/.*|AhrefsBot/.*|MJ12bot/.*|Mail.RU_Bot/.*|openstat.ru/.*|Nutch/.*)$") {
set req.http.Cookie = "frontend=crawler-session";
} else {
return (pipe);
}
}
if (true &&
req.url ~ ".*\.(?:css|js|jpe?g|png|gif|ico|swf)(?=\?|&|$)") {
unset req.http.Cookie;
unset req.http.X-Varnish-Faked-Session;
set req.http.X-Varnish-Static = 1;
return (lookup);
}
if (req.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?(?:adm|api|admin|cron\.php|ajax|ajaxbookmarks|onepagecheckout|catalog\/product_compare\/add|easycheckout|\.yml\.yml|sitemap\.xml|yandex\.xml|robots\.txt|landingpage|followupemail|searchindex|oneclickorder|fileuploader|sitemap_rent\.xml|nexus1c|platron|manualproductmerch|preorder|searchsphinx|sberbank)" ||
req.url ~ "\?.*__from_store=") {
return (pipe);
}
if (true &&
req.url ~ "(?:[?&](?:__SID|XDEBUG_PROFILE)(?=[&=]|$))") {
return (pass);
}
if (true && req.url ~ "[?&](utm_source|utm_medium|utm_campaign|utm_content|utm_term|gclid|cx|ie|cof|siteurl)=") {
set req.url = regsuball(req.url, "(?:(\?)?|&)(?:utm_source|utm_medium|utm_campaign|utm_content|utm_term|gclid|cx|ie|cof|siteurl)=[^&]+", "\1");
set req.url = regsuball(req.url, "(?:(\?)&|\?$)", "\1");
}
if(false) {
set req.http.X-Varnish-Cache-Url = req.url;
set req.url = req.http.X-Varnish-Origin-Url;
unset req.http.X-Varnish-Origin-Url;
}
return (lookup);
}
}
sub vcl_pipe {
unset bereq.http.X-Turpentine-Secret-Handshake;
set bereq.http.Connection = "close";
}
sub vcl_hash {
if (true && req.http.X-Varnish-Static) {
hash_data(req.url);
if (req.http.Accept-Encoding) {
hash_data(req.http.Accept-Encoding);
}
return (hash);
}
if(false && req.http.X-Varnish-Cache-Url) {
hash_data(req.http.X-Varnish-Cache-Url);
} else {
hash_data(req.url);
}
if (req.http.Host) {
hash_data(req.http.Host);
} else {
hash_data(server.ip);
}
hash_data(req.http.Ssl-Offloaded);
if (req.http.X-Normalized-User-Agent) {
hash_data(req.http.X-Normalized-User-Agent);
}
if (req.http.Accept-Encoding) {
hash_data(req.http.Accept-Encoding);
}
if (req.http.X-Varnish-Store || req.http.X-Varnish-Currency) {
hash_data("s=" + req.http.X-Varnish-Store + "&c=" + req.http.X-Varnish-Currency);
}
if (req.http.X-Varnish-Esi-Access == "private" &&
req.http.Cookie ~ "frontend=") {
hash_data(regsub(req.http.Cookie, "^.*?frontend=([^;]*);*.*$", "\1"));
}
if (req.http.X-Varnish-Esi-Access == "customer_group" &&
req.http.Cookie ~ "customer_group=") {
hash_data(regsub(req.http.Cookie, "^.*?customer_group=([^;]*);*.*$", "\1"));
}
return (hash);
}
sub vcl_hit {
}
sub vcl_fetch {
set req.grace = 15s;
set beresp.http.X-Varnish-Host = req.http.host;
set beresp.http.X-Varnish-URL = req.url;
if (req.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?") {
unset beresp.http.Vary;
set beresp.do_gzip = true;
if (beresp.status != 200 && beresp.status != 404) {
set beresp.ttl = 15s;
return (hit_for_pass);
} else {
if (beresp.http.Set-Cookie) {
set beresp.http.X-Varnish-Set-Cookie = beresp.http.Set-Cookie;
unset beresp.http.Set-Cookie;
}
unset beresp.http.Cache-Control;
unset beresp.http.Expires;
unset beresp.http.Pragma;
unset beresp.http.Cache;
unset beresp.http.Age;
if (beresp.http.X-Turpentine-Esi == "1") {
set beresp.do_esi = true;
}
if (beresp.http.X-Turpentine-Cache == "0") {
set beresp.ttl = 15s;
return (hit_for_pass);
} else {
if (true &&
bereq.url ~ ".*\.(?:css|js|jpe?g|png|gif|ico|swf)(?=\?|&|$)") {
set beresp.ttl = 86400s;
set beresp.http.Cache-Control = "max-age=86400";
} elseif (req.http.X-Varnish-Esi-Method) {
if (req.http.X-Varnish-Esi-Access == "private" &&
req.http.Cookie ~ "frontend=") {
set beresp.http.X-Varnish-Session = regsub(req.http.Cookie,
"^.*?frontend=([^;]*);*.*$", "\1");
}
if (req.http.X-Varnish-Esi-Method == "ajax" &&
req.http.X-Varnish-Esi-Access == "public") {
set beresp.http.Cache-Control = "max-age=" + regsub(
req.url, ".*/ttl/(\d+)/.*", "\1");
}
set beresp.ttl = std.duration(
regsub(
req.url, ".*/ttl/(\d+)/.*", "\1s"),
300s);
if (beresp.ttl == 0s) {
set beresp.ttl = 15s;
return (hit_for_pass);
}
} else {
set beresp.ttl = 86400s;
}
}
}
return (deliver);
}
}
sub vcl_deliver {
if (req.http.X-Varnish-Faked-Session) {
set resp.http.Set-Cookie = req.http.X-Varnish-Faked-Session +
"; expires=" + resp.http.X-Varnish-Cookie-Expires + "; path=/";
if (req.http.Host) {
if (req.http.User-Agent ~ "^(?:ApacheBench/.*|.*Googlebot.*|JoeDog/.*Siege.*|magespeedtest\.com|Nexcessnet_Turpentine/.*|SputnikBo/.*|Baiduspider/.*|YandexBot/.*|SemrushBot./*|Yahoo/.*|YandexMetrika/.*|DotBot/.*|BLEXBot/.*|AhrefsBot/.*|MJ12bot/.*|Mail.RU_Bot/.*|openstat.ru/.*|Nutch/.*)$") {
set resp.http.Set-Cookie = resp.http.Set-Cookie +
"; domain=" + regsub(req.http.Host, ":\d+$", "");
} else {
if(req.http.Host ~ "") {
set resp.http.Set-Cookie = resp.http.Set-Cookie +
"; domain=";
} else {
set resp.http.Set-Cookie = resp.http.Set-Cookie +
"; domain=" + regsub(req.http.Host, ":\d+$", "");
}
}
}
set resp.http.Set-Cookie = resp.http.Set-Cookie + "; httponly";
unset resp.http.X-Varnish-Cookie-Expires;
}
if (req.http.X-Varnish-Esi-Method == "ajax" && req.http.X-Varnish-Esi-Access == "private") {
set resp.http.Cache-Control = "no-cache";
}
if (false || client.ip ~ debug_acl) {
set resp.http.X-Varnish-Hits = obj.hits;
set resp.http.X-Varnish-Esi-Method = req.http.X-Varnish-Esi-Method;
set resp.http.X-Varnish-Esi-Access = req.http.X-Varnish-Esi-Access;
set resp.http.X-Varnish-Currency = req.http.X-Varnish-Currency;
set resp.http.X-Varnish-Store = req.http.X-Varnish-Store;
} else {
unset resp.http.X-Varnish;
unset resp.http.Via;
unset resp.http.X-Powered-By;
unset resp.http.Server;
unset resp.http.X-Turpentine-Cache;
unset resp.http.X-Turpentine-Esi;
unset resp.http.X-Turpentine-Flush-Events;
unset resp.http.X-Turpentine-Block;
unset resp.http.X-Varnish-Session;
unset resp.http.X-Varnish-Host;
unset resp.http.X-Varnish-URL;
unset resp.http.X-Varnish-Set-Cookie;
}
}
```

**Comment by miguelbalparda** [comment]
What have you tried so far to debug this issue? You pasted your entire VCL, where do you think the issue is in particular?

**Comment by aricwatson** [comment]
> for each cookie it is caching new pages
> so if i clear cookies in web browser, the first enter of page is also without cache

This is the default behavior if the '[Use VCL fix](https://github.com/nexcess/magento-turpentine/wiki/Configuration#general-options)' option is chosen - the first request is sent through to Magento to get a valid session. You can set it to use the observer fix, however this opens you up to some CSRF vulnerabilities.

**Comment by franzludilabel** [comment]
Hi,
@aricwatson On our setup (magento 1.9.2.1, varnish 4.0.3), we are using the observer fix (without it, we were having bugs of empty carts after login for a first time visitor) but despite the code related to first hit scenario wihout a frontend cookie being uncommented (it is commented if you choose to enable vcl fix), my tests prove that the first hit from a new visitor (without frontend cookie), for example on a product page, is not taken from Varnish cache... Is this the normal behavior in the current state of Turpentine ? Is there any workaround ?

It bothers me that the first hit is not taken from cache because this is the one that matters the most and Im scared it drives away mobile users because of slower loading page.

**Comment by aricwatson** [comment]
> So I just would like to know to be clear if this behavior is expected (first ever page view from a new visitor is not delivered by varnish cache) in the current state of the module ?

The trick here is in how you're warming your cache. Try this:

1) Go to page with new session, get an uncached page (Verify by looking at the response headers, look for 'Age: 0'
2) Clear cookies on that browser window
3) Reload the page. You should see a non-zero 'Age' header now, because the first request should have warmed the page cache for that URL.

How are you warming you page cache URLs?

**Comment by franzludilabel** [comment]
Hi Aric,

Alright, Do you mean that the version cache of every pages of the website must be created by someone who has not yet a session ?
If thats right, I dont know how Im supposed to do it on a live server with high traffics because the website users are warming the cache by themself if necessary every seconds.

Even if I set up a, lets say bot warmup, how can a bot be faster than the many visitors that are currently requesting every pages of the website. Wont be the bot late ?

**Comment by aricwatson** [comment]
> , Do you mean that the version cache of every pages of the website must be created by someone who has not yet a session ?

No - but it's important to understand that each page is cached by its URL *plus* other variables based on the request - such as the users User-Agent header (if UA normalization is turned *on*). 

If you look at the [vcl_hash](https://github.com/nexcess/magento-turpentine/blob/master/app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl#L232) subroutine, each time `hash_data` is called, another piece of data is being added to the key used to store that page in the page cache. Some of the key ones are User-Agent, Accept-Encoding, and the store/currency.

If two users request the same page - but they vary on one of those items used in the hash key - then they will not be hitting the same cache "bucket". The trick is minimizing the number of buckets in a way that makes sense for your site, and then setting up some sort of warming to keep those pages in the cache.

> how can a bot be faster than the many visitors that are currently requesting every pages of the website. Wont be the bot late ?

It's not that it's faster. The goal is to warm the cache so that as many pages as possible are in the cache when visitors arrive.

> By the way, here is the response header for a new session on an already cached page on my webserver 

Remember that the first request is *not* cached, so you won't see the 'Age' header...

I just pulled up that site and the homepage was cached on my visit: `Age:2927` - I had to reload the page after my first request get the cached page.

From there I went to http://www.ludilabel.fr/pack-etiquette-prenom-maternelle and saw `Age:1356` - so this page is also cached for me. Then I opened a different browser and went to that same URL. When I reloaded, I saw `Age:1443` which tells me that your cache isn't being split up by User-Agent issues.

**Comment by franzludilabel** [comment]
Hi Aric,

Kind of you to take time explaining those basics :) I will read in details what happens in vlc_hash subroutine just to be sure on what kind of cache is being generated. I will focus on the "currency" variable because I have no idea how it is working currently :)

Sorry for long post but based on what I read on many subjects of this github project, Im pretty sure there are confusions on this topic and it could help others if we figure exactly whats going on with that first ever http request and the session thing.

I understand I need to keep the number of buckets minimal in a way that makes sense for my site and it seems to be already the case since the UA is not among the variable taken into account for the hash key (the website is responsive so the code is the same whatever UA people are using, and as such I dont see the point of having separate bucks for every UA).

My concern about the speed of bot warning is resumed by your expression:

> when visitors arrive
because on a live server, it happens right after, im talking within a second, you clicked on the Magento Backoffice button to refresh varnish cache. So a scheduled warming bot, that executes lets say every 5 minute, will be too late. The warming bot needs to be executed right after the varnish cache has been emptied and hopefully within a second has requested every pages of the website, before the first visitor since varnish cache has been emptied request a page. 
That seems impossible so it means that some pages will be requested by the warming bot, so the cache version is generated on your planned conditions, and some pages will be requested by your visitors, whatever the situation they are in, having already a session, or without a session, etc.
But maybe Im missing the point. When you use a warming bot, does it overwrite whatever cache already generated by your visitors ? That way, even tough the cache had to be generated twice for many pages, at least you control the content of every pages being cached. 

When you say 

> I just pulled up that site and the homepage was cached on my visit: Age:2927 - I had to reload the page after my first request get the cached page.
You mean it was your first ever request and still you got a cached version of the page ? Because thats not what happens when I test it myself. If I delete the browser cookies and cache (ctrl+maj+supp on Chrome), then I refresh the homepage, I get the response headers that are in my previous post. There is no Age header but still I can tell its not an already cached page based on the TTFB value. For this particular homepage, I get a 180-200ms TTFB for the first ever request (without session) and 16ms TTFB for the second.

When you state 

> Remember that the first request is not cached, so you won't see the 'Age' header...

are you validating what I said in my first post? Which is: 

> the first hit from a new visitor (without frontend cookie), for example on a product page, is not taken from Varnish cache... but generated by Magento

That would explain why you had to **reload** the page to get Age:1443 when you tested the same page on an other browser, because the first request cant be cached because it needs to generate a frontend cookie that is specific to every user. Am I right ?

If Im right, this is what Im concerned about. Because, having the first ever request of first time visiting users, even if there is a valid reason because of the frontend cookie thing, users that we have made come with paid ads, or that are using mobile device with poor connectivity, having a TTFB of 600ms or way higher instead of 16-100ms (I know, this value depends on your connectivity) is terrible.
Do you agree with that? 

Because its the first impression that matters and if the first page you ever load of a website is taking seconds to get first data on your mobile device, you, as an impatient user, just close the page. And a caching solution is supposed to avoid that, right?

So, to resume, thanks to your help Aric :), I have two straightforward questions:
- Do you confirm that a new visiting user, with his first ever request of one of our webapp page, cant get a varnish cached version of the page because of cookie fronted specific to him that needs to be generated?
- Is there any workaround or simply impossible ?

Anyone is welcome to add its knowledge :)

And thank you for the module Turpentine, because without it, migrating to Magento would have been impossible. Tried softwares based caching but the results were better with Varnish.

**Comment by aricwatson** [comment]
> Do you confirm that a new visiting user, with his first ever request of one of our webapp page, cant get a varnish cached version of the page because of the cookie fronted that needs to be generated just for him?

Yes - *if* you use the "VCL Fix" - if you prefer to avoid this behavior you can use the "Observer fix" - which will disable some CSRF protection. We opted to make the VCL fix the default and to choose security over performance in this regard, but the choice is up to you. 

> Is there any workaround or simply impossible ? Because there are somes lines in the .vcl file generated by turpentine that suggest there was a solution to resolve this problem. And those lines are commented or not depending your choice of configuration of the "vlc fix" option that you have in the module Turpentine section in the Back Office of Magento.

Originally, Turpentine got around this problem by generating session keys in the VCL, which Magento would accept. The problem then was discovered that on the first page load, 'add to cart' buttons would *not* work. You can read about that here: https://github.com/nexcess/magento-turpentine/issues/345 . It was really only a problem if the user's first page request was a page with an add to cart button - however this is quite likely given that most advertising would tend to push users to a page with an add to cart button!


> having a TTFB of 600ms or way higher instead of 16-100ms (I know, this value depends on your connectivity) is terrible.
Do you agree with that?

Yes, it was not an ideal solution. However, we always tell users that you should not pursue using Varnish *only* for performance. You need to use Varnish on a site that is *already optimized* as much as possible. Varnish can have impressive page load benefits, but it's primary benefit is in improving *concurrency* - i.e. how many concurrent users your site can handle at the same time. Varnish/Turpentine will make your site able to handle far higher loads of users than otherwise is the case.

**Comment by franzludilabel** [comment]
Hi Aric,

Yeah, thats what I understood from reading github documentation, but in fact we configured on our website the "observer fix" option (it fixed a bug that we had with customers not able to stay connected and keep their cart right after checkout login if that was their first visit, especially on firefox), but still the page delivered doesnt seem to come from the varnish cache on the first visit. On reload, the TTFB is way better. But maybe I'm mistaken, maybe there is some cache involved, because the TTFB is around 300ms for the homepage, which is maybe lower than if the page has been generated by Magento. I will look into it.

Yeah, on all in all, I'm pretty satisfied with the results we already have. The TTFB of most pages of our website is most of the case better than most of our biggest competitors.

Thank you for your explanations and all the time you spent to enlighten us :)
