### ISSUE TITLE
Client or Admin login does not work the first time you try with Varnish + Nginx SSL Proxy Termination

### ISSUE THREAD

**Issue by rafaeljuzwiak** [nexcess/magento-turpentine#1279]
Hi everyone, I am running with an issue that I could not find any solution, and I am at the point where I am not sure if it is not a bug with the template for Varnish 4.0 here in the devel branch.

I added a Nginx Proxy in front of my Varnish in order to "give" the capability of HTTPs and still hit the cache, I follow every tutorial in this github page to setup this scenario, I tried with Pound, Apache2, and Nginx proxies and all has the same behavior.

When I try to login in the magento backend, or as a regular customer in the frontend, the first time I try does not work (using https), I get redirect back to the login page. However, if I try a second time it works, and the next tries also works with no problem, it is always just the first attempt that does not works, and the following ones works like a charm.

I reproduced the issue by removing all the cookies from my browser for that domain, when I do that the same behavior happen again (first time does not work, and the following tries works with no problem).
It seems to be an issue with the form_key generated by Magento and the ESI, I am not really sure, I tried to do proxies with all 3 softwares, and all of them gives exactly the same behavior.

Here is some of the configuration I am performing the tests.

Nginx proxy configuration:
`server {
    listen              8443;
    server_name         my domain here;
    ssl                 on;
    ssl_certificate     my certificate here;
    ssl_certificate_key my certificate key here;

    location / {
        proxy_pass http://127.0.0.1:6081;
        proxy_set_header X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header Ssl-Offloaded "1";
    }
}
`
In my magento Offloader header I have the HTTP_SSL_OFFLOADED as said it should be in this repo tutorial for nginx ssl proxy.

For my varnish configuration, I have up the configuration the Tupertine module generates for Version 4, here it is:

`vcl 4.0;
C{
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <pthread.h>
static pthread_mutex_t lrand_mutex = PTHREAD_MUTEX_INITIALIZER;
void generate_uuid(char* buf) {
pthread_mutex_lock(&lrand_mutex);
long a = lrand48();
long b = lrand48();
long c = lrand48();
long d = lrand48();
pthread_mutex_unlock(&lrand_mutex);
sprintf(buf, "frontend=%08lx%04lx%04lx%04lx%04lx%08lx",
a,
b & 0xffff,
(b & ((long)0x0fff0000) >> 16) | 0x4000,
(c & 0x0fff) | 0x8000,
(c & (long)0xffff0000) >> 16,
d
);
return;
}
}C
import std;
import directors;
backend default {
.host = <my server ip here>;
.port = "8080";
.first_byte_timeout = 300s;
.between_bytes_timeout = 300s;
}
backend admin {
.host = <my admin backend ip here>;
.port = "8080";
.first_byte_timeout = 21600s;
.between_bytes_timeout = 21600s;
}
acl crawler_acl {
"127.0.0.1";
}
acl debug_acl {
<my debug ip here>
}
/* -- REMOVED
sub generate_session {
if (req.url ~ ".*[&?]SID=([^&]+).*") {
set req.http.X-Varnish-Faked-Session = regsub(
req.url, ".*[&?]SID=([^&]+).*", "frontend=\1");
} else {
C{
char uuid_buf [50];
generate_uuid(uuid_buf);
static const struct gethdr_s VGC_HDR_REQ_VARNISH_FAKED_SESSION =
{ HDR_REQ, "\030X-Varnish-Faked-Session:"};
VRT_SetHdr(ctx,
&VGC_HDR_REQ_VARNISH_FAKED_SESSION,
uuid_buf,
vrt_magic_string_end
);
}C
}
if (req.http.Cookie) {
std.collect(req.http.Cookie);
set req.http.Cookie = req.http.X-Varnish-Faked-Session +
"; " + req.http.Cookie;
} else {
set req.http.Cookie = req.http.X-Varnish-Faked-Session;
}
}
sub generate_session_expires {
C{
time_t now = time(NULL);
struct tm now_tm = *gmtime(&now);
now_tm.tm_sec += 3600;
mktime(&now_tm);
char date_buf [50];
strftime(date_buf, sizeof(date_buf)-1, "%a, %d-%b-%Y %H:%M:%S %Z", &now_tm);
static const struct gethdr_s VGC_HDR_RESP_COOKIE_EXPIRES =
{ HDR_RESP, "\031X-Varnish-Cookie-Expires:"};
VRT_SetHdr(ctx,
&VGC_HDR_RESP_COOKIE_EXPIRES,
date_buf,
vrt_magic_string_end
);
}C
}
-- */
sub vcl_init {
}
sub vcl_recv {
std.syslog(180, "Varnish Request " + req.http.host + req.url);
if (req.http.host + req.url ~ <my url goes here>){
std.syslog(180, "Varnish Reply for " + req.http.host + req.url);
if (req.restarts == 0) {
if (req.http.X-Forwarded-For) {
set req.http.X-Forwarded-For =
req.http.X-Forwarded-For + ", " + client.ip;
} else {
set req.http.X-Forwarded-For = client.ip;
}
}
if (!true || req.http.Authorization ||
req.method !~ "^(GET|HEAD|OPTIONS)$" ||
req.http.Cookie ~ "varnish_bypass=1") {
return (pass);
}
if(false) {
set req.http.X-Varnish-Origin-Url = req.url;
}
set req.url = regsuball(req.url, "(.*)//+(.*)", "\1/\2");
if (req.http.Accept-Encoding) {
if (req.http.Accept-Encoding ~ "\*|gzip") {
set req.http.Accept-Encoding = "gzip";
} else if (req.http.Accept-Encoding ~ "deflate") {
set req.http.Accept-Encoding = "deflate";
} else {
unset req.http.Accept-Encoding;
}
}
if (req.url ~ "^(/media/|/skin/|/js/)(?:(?:index|litespeed)\.php/)?") {
set req.http.X-Turpentine-Secret-Handshake = "1";
if (req.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?admin") {
set req.backend_hint = admin;
return (pipe);
} else {
}
if (req.http.Cookie ~ "\bcurrency=") {
set req.http.X-Varnish-Currency = regsub(
req.http.Cookie, ".*\bcurrency=([^;]*).*", "\1");
}
if (req.http.Cookie ~ "\bstore=") {
set req.http.X-Varnish-Store = regsub(
req.http.Cookie, ".*\bstore=([^;]*).*", "\1");
}
if (req.url ~ "/turpentine/esi/get(?:Block|FormKey)/") {
set req.http.X-Varnish-Esi-Method = regsub(
req.url, ".*/method/(\w+)/.*", "\1");
set req.http.X-Varnish-Esi-Access = regsub(
req.url, ".*/access/(\w+)/.*", "\1");
if (req.http.X-Varnish-Esi-Method == "esi" && req.esi_level == 0 &&
!(false || client.ip ~ debug_acl)) {
return (synth(403, "External ESI requests are not allowed"));
}
}
if (req.http.Cookie !~ "frontend=" && !req.http.X-Varnish-Esi-Method) {
if (client.ip ~ crawler_acl ||
req.http.User-Agent ~ "^(?:ApacheBench/.*|.*Googlebot.*|JoeDog/.*|.*Siege/.*|magespeedtest\.com|Nexcessnet_Turpentine/.*|.*PTST.*)$") {
set req.http.Cookie = "frontend=crawler-session";
} else {
return (pipe);
}
}
if (true &&
req.url ~ ".*\.(?:css|js|jpe?g|png|gif|ico|swf)(?=\?|&|$)") {
unset req.http.Cookie;
unset req.http.X-Varnish-Faked-Session;
set req.http.X-Varnish-Static = 1;
return (hash);
}
if (req.url ~ "^(/media/|/skin/|/js/)(?:(?:index|litespeed)\.php/)?(?:admin|api|cron\.php)" ||
req.url ~ "\?.*__from_store=") {
return (pipe);
}
if (true &&
req.url ~ "(?:[?&](?:__SID|XDEBUG_PROFILE)(?=[&=]|$))") {
return (pass);
}
if (req.url ~ "[?&](utm_source|utm_medium|utm_campaign|gclid|cx|ie|cof|siteurl)=") {
set req.url = regsuball(req.url, "(?:(\?)?|&)(?:utm_source|utm_medium|utm_campaign|gclid|cx|ie|cof|siteurl)=[^&]+", "\1");
set req.url = regsuball(req.url, "(?:(\?)&|\?$)", "\1");
}
if (true && req.url ~ "[?&](utm_source|utm_medium|utm_campaign|utm_content|utm_term|gclid|cx|ie|cof|siteurl)=") {
set req.url = regsuball(req.url, "(?:(\?)?|&)(?:utm_source|utm_medium|utm_campaign|utm_content|utm_term|gclid|cx|ie|cof|siteurl)=[^&]+", "\1");
set req.url = regsuball(req.url, "(?:(\?)&|\?$)", "\1");
}
if(false) {
set req.http.X-Varnish-Cache-Url = req.url;
set req.url = req.http.X-Varnish-Origin-Url;
unset req.http.X-Varnish-Origin-Url;
}
return (hash);
}
}
else{
return (pass);
}
}
sub vcl_pipe {
unset bereq.http.X-Turpentine-Secret-Handshake;
set bereq.http.Connection = "close";
}
sub vcl_hash {
std.log("vcl_hash start");
if (true && req.http.X-Varnish-Static) {
std.log("hash_data static file - req.url: " + req.url);
hash_data(req.url);
if (req.http.Accept-Encoding) {
std.log("hash_data static file - Accept-Encoding: " + req.http.Accept-Encoding);
hash_data(req.http.Accept-Encoding);
}
std.log("vcl_hash end return lookup");
return (lookup);
}
if(false && req.http.X-Varnish-Cache-Url) {
hash_data(req.http.X-Varnish-Cache-Url);
std.log("hash_data - X-Varnish-Cache-Url: " + req.http.X-Varnish-Cache-Url);
} else {
hash_data(req.url);
std.log("hash_data - req.url: " + req.url );
}
if (req.http.Host) {
hash_data(req.http.Host);
std.log("hash_data - req.http.Host: " + req.http.Host);
} else {
hash_data(server.ip);
}
std.log("hash_data - req.http.Ssl-Offloaded: " + req.http.Ssl-Offloaded);
hash_data(req.http.Ssl-Offloaded);
if (req.http.X-Normalized-User-Agent) {
hash_data(req.http.X-Normalized-User-Agent);
std.log("hash_data - req.http.X-Normalized-User-Agent: " + req.http.X-Normalized-User-Agent);
}
if (req.http.Accept-Encoding) {
hash_data(req.http.Accept-Encoding);
std.log("hash_data - req.http.Accept-Encoding: " + req.http.Accept-Encoding);
}
if (req.http.X-Varnish-Store || req.http.X-Varnish-Currency) {
hash_data("s=" + req.http.X-Varnish-Store + "&c=" + req.http.X-Varnish-Currency);
std.log("hash_data - Store and Currency: " + "s=" + req.http.X-Varnish-Store + "&c=" + req.http.X-Varnish-Currency);
}
if (req.http.X-Varnish-Esi-Access == "private" &&
req.http.Cookie ~ "frontend=") {
std.log("hash_data - frontned cookie: " + regsub(req.http.Cookie, "^.*?frontend=([^;]*);*.*$", "\1"));
hash_data(regsub(req.http.Cookie, "^.*?frontend=([^;]*);*.*$", "\1"));
}
std.log("vcl_hash end return lookup");
return (lookup);
}
sub vcl_hit {
}
sub vcl_backend_response {
set beresp.grace = 15s;
set beresp.http.X-Varnish-Host = bereq.http.host;
set beresp.http.X-Varnish-URL = bereq.url;
if (bereq.url ~ "^(/media/|/skin/|/js/)(?:(?:index|litespeed)\.php/)?") {
unset beresp.http.Vary;
set beresp.do_gzip = true;
if (beresp.status != 200 && beresp.status != 404) {
set beresp.ttl = 15s;
set beresp.uncacheable = true;
return (deliver);
} else {
if (beresp.http.Set-Cookie) {
set beresp.http.X-Varnish-Set-Cookie = beresp.http.Set-Cookie;
unset beresp.http.Set-Cookie;
}
unset beresp.http.Cache-Control;
unset beresp.http.Expires;
unset beresp.http.Pragma;
unset beresp.http.Cache;
unset beresp.http.Age;
if (beresp.http.X-Turpentine-Esi == "1") {
set beresp.do_esi = true;
}
if (beresp.http.X-Turpentine-Cache == "0") {
set beresp.ttl = 15s;
set beresp.uncacheable = true;
return (deliver);
} else {
if (true &&
bereq.url ~ ".*\.(?:css|js|jpe?g|png|gif|ico|swf)(?=\?|&|$)") {
set beresp.ttl = 28800s;
set beresp.http.Cache-Control = "max-age=28800";
} elseif (bereq.http.X-Varnish-Esi-Method) {
if (bereq.http.X-Varnish-Esi-Access == "private" &&
bereq.http.Cookie ~ "frontend=") {
set beresp.http.X-Varnish-Session = regsub(bereq.http.Cookie,
"^.*?frontend=([^;]*);*.*$", "\1");
}
if (bereq.http.X-Varnish-Esi-Method == "ajax" &&
bereq.http.X-Varnish-Esi-Access == "public") {
set beresp.http.Cache-Control = "max-age=" + regsub(
bereq.url, ".*/ttl/(\d+)/.*", "\1");
}
set beresp.ttl = std.duration(
regsub(
bereq.url, ".*/ttl/(\d+)/.*", "\1s"),
300s);
if (beresp.ttl == 0s) {
set beresp.ttl = 15s;
set beresp.uncacheable = true;
return (deliver);
}
} else {
set beresp.ttl = 3600s;
}
}
}
return (deliver);
}
}
sub vcl_deliver {
if (req.http.X-Varnish-Faked-Session) {
set resp.http.Set-Cookie = req.http.X-Varnish-Faked-Session +
"; expires=" + resp.http.X-Varnish-Cookie-Expires + "; path=/";
if (req.http.Host) {
if (req.http.User-Agent ~ "^(?:ApacheBench/.*|.*Googlebot.*|JoeDog/.*|.*Siege/.*|magespeedtest\.com|Nexcessnet_Turpentine/.*|.*PTST.*)$") {
set resp.http.Set-Cookie = resp.http.Set-Cookie +
"; domain=" + regsub(req.http.Host, ":\d+$", "");
} else {
if (req.http.Host ~ "" && "" ~ "..") {
set resp.http.Set-Cookie = resp.http.Set-Cookie +
"; domain=";
} else {
set resp.http.Set-Cookie = resp.http.Set-Cookie +
"; domain=" + regsub(req.http.Host, ":\d+$", "");
}
}
}
set resp.http.Set-Cookie = resp.http.Set-Cookie + "; httponly";
unset resp.http.X-Varnish-Cookie-Expires;
}
if (req.http.X-Varnish-Esi-Method == "ajax" && req.http.X-Varnish-Esi-Access == "private") {
set resp.http.Cache-Control = "no-cache";
}
if (false || client.ip ~ debug_acl) {
set resp.http.X-Varnish-Hits = obj.hits;
set resp.http.X-Varnish-Esi-Method = req.http.X-Varnish-Esi-Method;
set resp.http.X-Varnish-Esi-Access = req.http.X-Varnish-Esi-Access;
set resp.http.X-Varnish-Currency = req.http.X-Varnish-Currency;
set resp.http.X-Varnish-Store = req.http.X-Varnish-Store;
} else {
unset resp.http.X-Varnish;
unset resp.http.Via;
unset resp.http.X-Powered-By;
unset resp.http.Server;
unset resp.http.X-Turpentine-Cache;
unset resp.http.X-Turpentine-Esi;
unset resp.http.X-Turpentine-Flush-Events;
unset resp.http.X-Turpentine-Block;
unset resp.http.X-Varnish-Session;
unset resp.http.X-Varnish-Host;
unset resp.http.X-Varnish-URL;
unset resp.http.X-Varnish-Set-Cookie;
}
}
`

I am sorry if that is not a bug, but some miss configuration, I am reaching out using here because it really seems like a bug, I have used 3 different proxies, and they are all giving the same behavior with the tupertine module.

Thanks.

**Comment by rafaeljuzwiak** [comment]
Sorry for the minified code from the VCL, I just copied and pasted the code the module generates, and that is how it comes.

**Comment by miguelbalparda** [comment]
I don't have much experience with nginx, but this seems to be something caused by the VCL fix we implemented. I suggest you to read the documentation about that or even try to disable it from the admin. Also, can you try to do the same with Vanrish 3?

**Comment by rafaeljuzwiak** [comment]
I am have to install a new server in order to test with varnish 3, I will try to disable the VCL fix, and if does not work I will try to setup a varnish 3 in order to test. I get back with the findings in a few.

Thanks

**Comment by rafaeljuzwiak** [comment]
Btw, it is just over HTTPs, with HTTP all forms works with no problem at all

**Comment by miguelbalparda** [comment]
That might be an indicator of a problem with the https config probably.

**Comment by rafaeljuzwiak** [comment]
That is what I thought, but I replicate exactly the same configuration there is in every tutorial, and it still happening. Disabling the VCL fix did not worked, I will setup a Varnish 3 and test.

The tutorials are:
Using Pound: https://github.com/nexcess/magento-turpentine/wiki/SSL_Support
Using NGinx: https://github.com/nexcess/magento-turpentine/issues/35

And for the apache I just did my self using the nginx and pound as base.

**Comment by rafaeljuzwiak** [comment]
I believe I found something that may be causing that.
I am logging some requests in my Varnish, and one thing I notice is that client.ip value is 127.0.0.1, which is caused by the nginx proxy since it is actually nginx who is performing the request to varnish.

However, I am setting in my nginx the X-Forwarded-For header as well, and I have real ip active, if I put the following line in my vcl in order to check the values
`std.syslog(6, "Client: " + client.ip);
    std.syslog(6, "X-Forwarded-For: " + req.http.X-Forwarded-For);`

I get the X-Forwarded-For with the correct ip, but the client.ip as 127.0.0.1
I am not sure now, should the client.ip be changed by the X-Forwarded-For, or the client.ip will never change?

**Comment by rafaeljuzwiak** [comment]
I found the reason, but unfortunately not the solution yet.
I started to fill some functions with print_r in order to check each step of the way, and I found that for some reason the form_key does not match when the form is posted.

At "app/code/core/Mage/Customer/controllers/AccountController", function loginPostAction, the first thing is a check of the form_key argument, checking is the form_key coming from the form matches with the form_key in the session of that user,  and for some reason, when doing over HTTPs it does not match, and the functions returns there. But the weird is that after the first time the form_key always match, just the first time always do that.

**Comment by rafaeljuzwiak** [comment]
You guys can close this issue. Just for feedback, after a while changing core files, I got to the source of the problem at app/code/core/Mage/Core/Model/Session/Abstract/Varien.php, specifically the part where Magento checks for the Secure Cookie "frontend_cid" in order to prevent Man in The Middle attacks. After I got to this location, I found another issue in this repo issues about people losing carts (https://github.com/nexcess/magento-turpentine/issues/725).

Actually the issue is the same, the cause to the lost of carts in that case it is because magento resets the session for some reason that I could not find. The double login it is just an addition issue to the session being reset.

Unfortunately I could not find a proper solution other than rewriting the Varien.php class, and removing the session reset it is done in that section.

Thanks anyway.

**Comment by rafaeljuzwiak** [comment]
SOLVED!!!

So, after hours looking again, and again because I was unhappy with rewrite session solution, I finally found it!!

The problem is with the VCL template, and that is probably happening with Version 3 template as well if you want to use a proxy for TLS/SSL support.
At line 273 on the template, the module addeds into varnish hash the frontend cookie:

`if (req.http.X-Varnish-Esi-Access == "private" &&
            req.http.Cookie ~ "frontend=") {
        hash_data(regsub(req.http.Cookie, "^.*?frontend=([^;]*);*.*$", "\1"));
        {{advanced_session_validation}}
    }`

However, it checks for the HTTP cookie only, and as up to magento 1.9.1 magento team added the new "frontend_cid" cookie for secure connections. So the solution for the problem is replicate this if, and add a new hash in case the cookie for HTTPs (frontend_cid) is set, like that:

`if (req.http.X-Varnish-Esi-Access == "private" &&
            req.http.Cookie ~ "frontend_cid=") {
        hash_data(regsub(req.http.Cookie, "^.*?frontend_cid=([^;]*);*.*$", "\1"));
        {{advanced_session_validation}}
    }`

After that everything works great, you guys should check the module and make the proper updates, thanks.

**Comment by Petce** [comment]
@rafaeljuzwiak you are getting closer to the issue but I'm afraid your solution doesn't really fix the problem.

I also came across this solution when I was trying to crack the issue but the problem with this is that the key to the hash in the cookie cannot be injected into the Magento Session from Varnish.

That is to say, any user who is a first time visitor to the site (no cookies), will be given cookies by Varnish. But these cookie hashes are not recognised by Magento because they are not in the session hash.

This means that the first attempt to actually communicate with the server, which is typically through a POST request, will result in a SESSION check failure.

The normal default response for Magento in this situation is to ignore the request, remove the cookies from the user's browser and then issue new cookies.

This is why after the first attempt of adding an item to the cart or trying to log in, normal functionality is restored.

The fundamental issue is simple. Varnish cannot be responsible for giving the user its session cookies. The reason being is that Varnish is detached from the Magento system, where the session information is managed.

It's been a while since I checked, but the "proper" fix for this issue as per this GitHub project, was to let the first visit to the site be an uncached visit. This would allow the server to initialize a session and issue cookies to the user that actually validate true.

I personally was not happy with this solution as I don't want any visit to my site to be slow. Instead, I reworked the way sessions work so that if a session fails, rather than ignore the request, Magento should initialize a new session and then perform the request.

**Comment by miguelbalparda** [comment]
> After that everything works great, you guys should check the module and make the proper updates, thanks.

@rafaeljuzwiak if you think this is a proper solution please open a pull request so other members of the community can check it and see if it is suitable. From what @Petce said, it seems not to be but we can still check it once you submit the PR.

**Comment by Accurno** [comment]
I wanted to share the solution I've resorted in to. It's not a clean fix, but it's quite simple to do. Also, i'm not sure if there will be a security flaw with this way. I haven't really analyse it properly so apologise for suggesting this if ever this is not a good solution in terms of security.  

We all know that with the VCL Fix set to enabled, during the very first visit to a page (no previous session), an actual Magento page request will be made instead of getting the cached one in Varnish. This is to make sure that a REAL MAGENTO SESSION and a REAL FORM KEY will be created for CSRF protection purposes.

However, with this setting turned on, first visit to the page will be slow because it's Magento. 2nd visit to the page will be slightly slow because of ESI stuff that needs to be done for the current session. Then the 3rd visit to the page will be the full page cached from Varnish.


Now about the solution I've used. This is just basically as follows:

_1. VCL Fix disabled

2. Create a URL (ex. www.example.com/formkey) on the website where in upon being visited it will create a COOKIE that will have the REAL FORM KEY as the value. Set that cookie to expire at the same time as the Magento cookie life time. You will be needing to create a Magento extension for this with a controller that will set or create the said form key cookie. Have that URL exempted on Varnish or Turpentine.

3. Create a javascript code that will access the "www.example.com/formkey" ASYNCHRONOUSLY.

4. Have the javascript AJAX code to run on DOM load and check the "REAL FORM KEY COOKIE" if its in existence and not yet expired. If it's non existing or expired, have the AJAX code access "www.example.com/formkey" and on success, set all the "form_key" element on the current page to be replaced with the form key from the cookie.

5. If the form key cookie is existing and non expired, just have the code replace all the form key on the current page. Special code will be needed with the product page's "add to cart form" action URL._



So the summary is when a cached page is:

**VCL Fix Enabled:**
1st page visit (slow - real Magento request)     ->     2nd visit (bit slow)     ->     3rd visit and so on (fast)
* No problem with form keys



**VCL Fix disabled:**
1st page visit (fast)     ->     2nd visit (bit slow)     ->     3rd visit and so on (fast)
* WILL HAVE problems with form keys on FIRST FORM POST try.
* Cached product page's CSRF protection will be disabled. Will still be able to perform add to cart.
* 3rd party extensions that uses form keys won't work on 1st try.


**VCL Fix disabled with REAL Magento session and form key being done asynchronously:**
1st page visit (fast)     ->     2nd visit (bit slow)     ->     3rd visit and so on (fast)
* WILL NOT HAVE problems with form keys on FIRST FORM POST try.
* Cached product page's CSRF protection will be ENABLED.
* 3rd party extensions that uses form keys will work normally.


At the time of this post, Turpentine's current way is to set or alter the form keys via ESI way. I guess the reason would be to ensure faster execution, however the downside would be making fake non-working form keys, until an actual Magento request has been done.


The AJAX way is just a quick fix and hopefully on the next update, it will be addressed properly.

**Comment by joazvsoares** [comment]
Will you create a PR for this solution?
