### ISSUE TITLE
ESI Blocks Returning 0 Bytes

### ISSUE THREAD

**Issue by thekingloo** [nexcess/magento-turpentine#1349]
Can someone please help with this. This is from my developer. 

http://www.greeku.com/alpha-chi-omega/turpentine/esi/getBlock/method/ajax/access/private/ttl/0/hmac/22baecf6bb5e870f046c357b6ab21fbef8e23ae7fb726be2096c91dcc11f75fd/data/E9Lmgv-cVxfBAYN-gJohSSrQcnYUbWyTLEv4l7EU.C5BNRMz-ZHs6xLDUrLt3oaFOQUxJCM1bxA3zO9I-ef5khVjKprSPOOnr8Zq4KuzKwc.wStWFNUDjBgmoiOj0EsXI9YZaHEuMxUgFewj8Kcpqsh1O5HV4SLWPpU7I1WsMxu.okIOX.AZZIifkegUphyeB213JbzJBGuLJNvPN8NESg4nAnMuYPdNhr.lFsjwLE9zo0OziL1XZSg.wzPwVi0VixvF8Eftc-Yb7QbKzriVeUa0YDzGjukq7KHUv2TlX8CPpfbnLi0xqNWNpwhfVlHk9oECFZyFl6gvyqQ54FnLog==/

http://www.greeku.com/alpha-chi-omega/turpentine/esi/getBlock/method/ajax/access/private/ttl/0/hmac/b904d8f71efd2f3020a7a1ec668f64c497356f791d9a952de0279eaebe80066f/data/RtukwkYP50py5wDDKi73-nCNB.-WEUsof3NeEFNTVtJLjt5Gdzi24gzPX1nWsZQa9jVmt9h0QyGZHiHn2H4L-UpQRSnoOWemCDkken8lJHrb1r0reJ7DlQQ0-r.0fnRNLhcXJZ4J4ZfnCwX3e8PxyCPXFmi4fNrmgy9-pBVjS57bSIFnh1uYFUBVKF4DlNae7yAKJ1l2ta9JDZoY1-u10VINTdPhTfjjbnGX3CjNGylUQ.hCgxyEdii0xTwi4CYyK.SUV36xFwkNOP743Fuh1Yw7KMGP40X-ILAoTyXitS4fIetUzAe1MUFPWUsoFbt29DdfAilvM3nHOzV-ABA2FQ==/

these are ESI requests. but they are not cached because how Turpentire interpretate this URL. look on /ttl/0/  part. 0 is how long to cache. So means never. However if I change that to let say 120 I see it’s cached for 2 minutes.

This is generated by Turpentine. if it’s hardcoded then why. if not then should be some setting to set minimal cache time, because it’s uniq object for a single user. and it ’s probably requested many time until user is on site. So makes sense to cache it for few minutes
this doesn’t not return anything. it’s something with session

**Comment by miguelbalparda** [comment]
There is a tool in this repo called [esi-decoder.php](https://github.com/nexcess/magento-turpentine/blob/8549a0f207c63e62c61570f81925bd574c63f2c5/contrib/tools/esi-decoder.php) where you can check which block generated this. This is also fully documented in the [Wiki](https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy) section where you can find a complete explanation on how the ttl is defined.

From your questions I can see you don't have much experience with this module so please keep in mind this is not a plug and play extension and that it might require you to read the documentation and twek your theme in order to make it work for your store.

**Comment by thekingloo** [comment]
MIguel, thank you for your response. Can I hire you to help optimize this a little more? Can you email me directly at daniel@greeku.com

**Comment by miguelbalparda** [comment]
No, I don't do paid consulting outside Nexcess. Tell your dev to take a look at the repo and post any questions here, this is a pretty active and well documented repo and the issue you are experiencing now was probably solved before.

**Comment by thekingloo** [comment]
Okay. Thanks Miguel

**Comment by thekingloo** [comment]
@miguelbalparda I have another question about Turpentine in Magento. There is an option for "Enable Site Crawler." If I enable that, is there a way to control the times of days that the site is crawled to warm the cache?
