### ISSUE TITLE
getBlock fails only when accessed through Varnish

### ISSUE THREAD

**Issue by keebs** [nexcess/magento-turpentine#1357]
My template is using the Cmsmart/megamenu extension.
Turpentine is installed throughout everything that I am describing.

The code causing the problem is:
$layout = $this->getLayout();
$this->setTemplate('cmsmart/megamenu/topmenu.phtml');
$head = $layout->getBlock('head');

If I access Magento directly, bypassing Varnish, but with turpentine still installed and the varnish cache enabled in the Mage admin, the header displays fine.

If I then access Magento though varnish, $layout return an object from the class: Mage_Core_Model_Layout
and $head is null.

Absolutely no coding, configuration, caches, etc were otherwise changed. All I did was access Magento bypassing varnish and then through varnish. Anyone have any idea what is happening here?

Running Mage 1.9.2.4. TY

**Comment by miguelbalparda** [comment]
This is not a plug and play extensions, some changes might be required in your theme in order to make it compatible with this extension. Take a look at the wiki and check the open and closed issues to see if anyone else had the same issue you are experiencing and report back please.

**Comment by keebs** [comment]
I've already spent a few hours looking for any similar issues and reading documentation and have been unable to find anything relevant. What I have given you is what I have been able to troubleshoot thus far. The Magento code is unchanged with and without bypassing Varnish so it seems somewhere something is detecting whether the request is actually through varnish or not and acting upon the code differently. I was hoping someone could explain what is happening and save a few more hours of debugging. Thanks anyway.

**Comment by miguelbalparda** [comment]
This issue is usually caused by an incompatible architecture of your menu with this module, most of this is explained [here](https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy). 

I'm also unable to understand how are you testing this, have you tried to insert this block via AJAX as explained in the wiki? 
Have you checked the closed issues? Trying to wrap the menu block with a block you can control is usually helps.

**Comment by keebs** [comment]
$head = $layout->getBlock('head');
was only being used to add a skin_js, so I moved the skin_js to the extensions xml layout file and just removed the line above completely.

Now it works through varnish, but the template (topmenu.phtml) is displayed twice.

I'll try ajax and see if it changes anything. TY

**Comment by keebs** [comment]
Ajax works! Now it only displays once....
Can you explain why using AJAX works?

**Comment by miguelbalparda** [comment]
Not really sure since it might vary between modules, but it usually means the module can't inject themselves via ESI and has to be loaded separately and not cached. Since you are using a menu my guess is that the way it's defined in the XML is somehow incompatible with Turpentine and it's generating a double include when the layout XML is built.
