### ISSUE TITLE
Not calling controller_action_predispatch

### ISSUE THREAD

**Issue by ZEDGR** [nexcess/magento-turpentine#1412]
Hello

I have seen the plugin is not calling the controller_action_predispatch.
I have found this because I am using the controller_action_predispatch_checkout_onepage_index event in my observers to check if a user has entered in checkout state.

Is any other event to check the checkout state ?

Thanks in advance!

**Comment by miguelbalparda** [comment]
Due to the nature of the module and how cache works, there are some pages that are loaded completely from Varnish and some events are not going to be fired. This is vastly covered in the Wiki and in other issues. Regarding your particular case, the checkout should be whitelisted. What have you tried so far to debug this? Have you searched the repo for similar issues?

**Comment by ZEDGR** [comment]
Sorry for the inconvenience it was wrong configuration from my side.
This event is working fine with turpentine
