### ISSUE TITLE
Some users can login some others cant!

### ISSUE THREAD

**Issue by marios1prot** [nexcess/magento-turpentine#222]
Good evening. I am using Magento 1.7.0.2 and Turpentine 0.5.3 . The same problem with this (https://github.com/nexcess/magento-turpentine/issues/169) occurs to me.In order to be able to log in again I have to delete the cookies and clear the back end cache memory.Is there any solution?
Thanks in advance

**Comment by harveychow** [comment]
We had the same issue. Problem is with people who to go example.com which then redirects to www.example.com (because it's set as base_url). Cookies then will be set on example.com and on www.example.com. We also tried redirecting in Nginx/Apache instead of Magento, but that wouldn't work either, because Varnish would still set the cookie. Only method is to redirect in Varnish or let example.com go to another server which redirects to www.example.com.

It would be great if nexcess could fix this in the default.vcl.

**Comment by CalamityJames** [comment]
@harveychow I managed to fix this on a clients site, the problem is that setting it in `.htaccess` (or nginx's equivalent) still allows Varnish to set the frontend cookie.

In the end I added the following to the `custom_include.vcl` file to get the 301 to happen at Varnish's end (obviously replace example.com with your URL):

## Varnish 3.0 syntax

````
sub vcl_recv {
    if (req.http.host == "example.com") {
        set req.http.host = "www.example.com";
        error 750 "http://" + req.http.host + req.url;
    }
}

sub vcl_error {
    if (obj.status == 750) {
        set obj.http.Location = obj.response;
        set obj.status = 301;
        return(deliver);
    }
}
````

## Varnish 4.0 Syntax

````
sub vcl_recv {
    if (req.http.host ~ "^example.com") {
        return (synth (750, ""));
    }
}

sub vcl_synth {
    if (resp.status == 750) {
        set resp.status = 301;
        set resp.http.Location = "http://www.example.com" + req.url;
        return(deliver);
    }
}
````

Hope this helps!
