### ISSUE TITLE
Mage 1.8  - Add to Cart not working, Please help

### ISSUE THREAD

**Issue by akh2013** [nexcess/magento-turpentine#345]
Hello,

At the outset, I will like to thank your team for a wonderful extension for caching Magento.

I recently upgraded my install from 1.7 to 1.8 CE.  After upgrade, when I add an item to a cart, the cart is empty.

I have checked cookies - the cookie domain, path etc. are ok.  Occassionaly I see that while switching between cached pages, the cookie frontend is available but path, domain etc. are blank.

Can you please guide me how to resolve this problem?  It is slightly urgent because I had to disable cache because cart stopped working.

Regards,

Akhil

**Comment by milansimek** [comment]
The issue still persists with the newer Turpentine version, but only in the following scenario:

1. Open incognito tab (or visit website for the first time)
2. Add product to cart
3. Cart is empty

You can see that the form key in the form action and the form key hidden input don't have the same key on the first visit.

However, if you come from another page on the website, or refresh the page one time, the form key will be correct in both the URL and hidden input. It means that this issue only happens with new customers, clicking the add to cart button on the first page they land on.

The module with the fix from @EvrijnSD works perfectly though!

**Comment by giacmir** [comment]
I have the same issue described by @milansimek

**Comment by aricwatson** [comment]
I can replicate this by doing the following
1) new incognito tab
2) go *directly* to the product page
3) add to cart -> leads to empty cart

If I go first to the homepage (for example) before going to the product page, add to cart works fine.

I'll see what I can do.

**Comment by aricwatson** [comment]
@paales vcl tweak for https://github.com/nexcess/magento-turpentine/issues/470 (perhaps in conjunction with PR https://github.com/nexcess/magento-turpentine/pull/516)   seems to fix this issue.

Here's his tweak:

> So replace:
```
if (req.http.Cookie !~ "frontend=") {
    if (client.ip ~ crawler_acl ||
            req.http.User-Agent ~ "^(?:{{crawler_user_agent_regex}})$") {
        # it's a crawler, give it a fake cookie
        set req.http.Cookie = "frontend=crawler-session";
    } else {
        # it's a real user, make up a new session for them
        call generate_session;
    }
}
```
> with
```
if (req.http.Cookie !~ "frontend=") {
    if (client.ip ~ crawler_acl ||
            req.http.User-Agent ~ "^(?:{{crawler_user_agent_regex}})$") {
        # it's a crawler, give it a fake cookie
        set req.http.Cookie = "frontend=crawler-session";
    } else {
        # it's a real user, make up a new session for them
        call generate_session;
        return (pipe);
    }
}
```

Can anyone please test and report back?

**Comment by paales** [comment]
@aricwatson Thanks for the response.
As mentioned [here](https://github.com/nexcess/magento-turpentine/issues/470#issuecomment-40589693), it doesn't *really* solve the issue, it just creates a pipe which disables varnish on the first page load. If you think I'm wrong, please let me know :)

**Comment by aricwatson** [comment]
Ah, yes it does appear so. Back to the drawing board!

**Comment by akh2013** [comment]
You know what? After grappling with magento for over 8 years..been using
them since their 0.98 beta i abandoned the project and built my own cart
ground up using java.  My conversions are up 300% ..took 4 months to build
but worth the effort.

**Comment by Krapulat** [comment]
@akh2013 can you show us your e-commerce and, if you know the reason, why your conversions are up 300%?

**Comment by aricwatson** [comment]
Just an update, we are still working on a fix for the form key issue.

**Comment by gewaechshaus** [comment]
@aricwatson - we did have some form key related issues also, please take a look at https://github.com/nexcess/magento-turpentine/issues/692

**Comment by aricwatson** [comment]
Hi all - got some more info on this one.

Yesterday my development machine froze and crashed for the first time in quite awhile. As a result, this morning when I sat down to work on this issue some more, I realized I hadn't started up Varnish. I did so, and this bug is gone. I cannot replicate it any more using the steps outlined above https://github.com/nexcess/magento-turpentine/issues/345#issuecomment-106061392

So, I hate to go with "*have you tried turning it off and back on again*" - but if you're currently seeing this bug and can reproduce it as outline, please try restarting Varnish and let us know!

**Comment by Krapulat** [comment]
@aricwatson Have you waited enough time? I think after a time the bug appears again.

**Comment by aricwatson** [comment]
Yes, just tested and the bug was back after 5-6 hours. Restarting varnishd took care of it. Does anyone have a feeling for how long before the error starts occurring again?

I wonder, has anyone seen this happening with the varnish 4.x fork? If not, perhaps the next step is to get that merged into the main branch and chalk this one up to a Varnish 3.x bug.

**Comment by loginid** [comment]
Just a note from me that this same problem has been occurring in my varnish/turpentine install as well (which is the latest varnish / turpentine).

@Verguetz - thanks for the fix. It's working for me too.

@aricwatson - maybe this should be included somewhere so that people know they need to apply the fix?  

Thanks.

**Comment by aricwatson** [comment]
Good idea, I'll update the docs to mention both of the available fixes - at least until we hopefully come up with a more permanent fix.

**Comment by miguelbalparda** [comment]
It seems #832 has a fix for this issue. would you mind giving it a try? It is on the devel branch until further testing.

**Comment by Petce** [comment]
This issue should not be closed. It is still prevalent and disabling CSFR, while a workaround, should not be considered the solution.

This bug should remain open until a real solution is created. In addition, A caveat should be clearly listed in the documentation as warning to all that this problem exists, and in terms that clearly state the symptoms. I for one, would not have used turpentine if I knew it would stop people from adding products to their carts the first time they try.

**You are dealing with peoples customers here, the first impression is vital, and not having a product added to the cart the first time a customer clicks an add to cart button, has the high probability of obliterating any possible chances of converting that customer.**

The issue is very easily replicated:
	1. Delete your frontend cookies for the Magento Store you wish to test.
	2. Refresh the page.
	3. Try to add an item to your now empty cart.
	4 System directs you to a cart is empty page.

**This problem will always re-manifest whenever the session dies or the cookie expires.**

The new frontend cookie issued to you by the Turpentine VCL is not a valid session. And it never will be unless you figure out how to force inject it into the Magento Session Engine at the first possible opportunity.

Any request to the server that is 'pipe'd will fix the bug, as it will give Magento a chance to create a session for the client. The obvious down fall to this is that the first visit will be a cache miss.

The best **workaround** on this thread is the one proposed by @paales, and dont mistake it, it is a workaround, and not a solution.

Somehow, for this to be a proper solution, A Magento Session has to be primed for the client on their first visit, and it needs to be injected into the cached response object.

I recommend this issue be re-opened and stickied.

**Comment by miguelbalparda** [comment]
I can understand what you mean @Petce. This is an ongoing development project, we are working hard to fix this and #832 was a good shot to test. If you think you can contribute with this in any way you are more than welcome. If your issue duplicates this, please close it.

**Comment by Petce** [comment]
I am very new to varnish, I have literally just picked it up in the last few days.

The only solution to the issue is to somehow prime a Session in the Magento Session Engine on a clients first visit.

Ideally, the first visit to the site should also be a cache hit.

This tells me that maybe a custom (possibly obfuscated) header to an ESI request could be used to prime the session.

I am looking in to the flow of Varnish right now to see if such a thing is possible.

**Comment by Petce** [comment]
Has anyone considered modifying the way cookies are issued so that cookies are only assigned once a customer attempts an action that requires a POST action?

This would however require some decent changes to both Turpentine and the VCL template.

**Comment by Petce** [comment]
Or better yet, leave everything as is. When the time comes to validate a session, if it fails, create a new session, complete the task.

If the client has a valid frontend cookie, there should be no problems.

If the client frontend cookie is invalid (as is the case with all first time visitors to the site when using Varnish), release that session, create a new one, and complete the requested task on that new session.

Does anyone see a problem with such logic? I will try and attempt to implement it.

**Comment by Petce** [comment]
I have changes that I want to propose as a work around for this issue but I have no clue how to use GitHub. Any pointers?

**Comment by miguelbalparda** [comment]
First fork the project and do your changes in your repository in the devel branch, where the most up-to-date version is. Then push your changes to your fork and once you are done, create a pull request between forks and point it to the devel branch here. If you need any more help, let me know.

**Comment by Petce** [comment]
Update on the error:

The issue we are seeing is produced by a number of errors occurring.

When a client visits the site for the first time, varnish issues a Session ID and puts it in the response header as a cookie called 'frontend'.

If the page that was called on that first visit has ESI blocks on it, they will be executed with the original request header that the client sent, this means that on the first page load for any client, ESI blocks cannot see what Session ID the client was given by Varnish. This means that all Form Keys that are shown on that first load will be incorrect.

This problem exasperates when the site is configured to SSL, that is, a secure protocol. In this situation, Magento issues a second cookie that is tied to a session variable called a 'frontend_cid'. If these values don't match up, Magento will issue you with a new Session via a new Session ID.

Other things, in addition, to the above, may cause the Session ID to roll onto a new hash if at some stage the Session doesn't validate correctly. This ultimately results in a Form Key validation error once the client attempts to perform a transaction on the server, typically any request to the server not made with a GET or HEAD method. Once this transaction attempt it made, the new and correct cookies and sessions are 'pipe'd to the client however the original request failed and was abandoned. This is why if the client then attempts to add an item to his cart again, the system will work.

To continuously replicate the issue, again, follow these steps:
1. Delete your frontend cookies for the Magento Store you wish to test.
2. Refresh the page.
3. Try to add an item to your now empty cart.
4 System directs you to a cart is empty page.

**Comment by aricwatson** [comment]
I just committed to *devel* a change to the default VCL that implements @paales change to disable the session generation code. 

Unfortunately, this comes at a small performance cost, as Varnish is disabled on the first page load for new visitors. We were unable to find a better solution for this problem as of yet, and did not want to disabled CRSF protection.

This also fixes issues with multiple sessions being created (i.e. https://github.com/nexcess/magento-turpentine/issues/806)

Please test and let us know if you see any problems.

**Comment by miguelbalparda** [comment]
+1

**Comment by Petce** [comment]
@aricwatson @miguelbalparda While @paales fix is better than having nothing, I do not understand why you havn't tried to work in the fix that I proposed in Pull Request #839. I understand the lack of desire to include a modification to a Magento Super Class but please do not forget that the current live build that is downloaded and used by people from the Magento repositories has in itself got an override of the Super Class ```Mage_Core_Model_Session``` that is in part, a factor of this issue.

Please look at the proposed change again, it is not that difficult, but most importantly, it allows a first visit to the site to be a cache hit.

**Comment by paales** [comment]
Just to chip in. With my workaround the performance isn't very good and defeats the purpose of using turpentine over a PHP-based caching module. Our conclusion was, varnish is highly complex and not worth it for most project, better invest in a faster server and set up HHVM in combination with a PHP-based FPC.

**Comment by aricwatson** [comment]
@Petce Your fix is quite good, however we decided against it primarily because we do not want Turpentine to do anything to reduce/compromise Magento's security.

@paales There certainly is a performance penalty with this change. However we were also getting reports of performance issues relating to unnecessary session creation, which this change fixes. We're planning on doing some performance testing to see just how much of a hit this may cause. 

The old session generation code is still in the vcl template, and if people wish to "put it back" it should merely be a matter of uncommenting that code and re-applying the VCL. Meanwhile, we'll leave this issue open while we continue to look for a better fix.

**Comment by m-overlund** [comment]
Has anyone had time to test on Magento 1.9.2.0?
Changelog states: "Cross-site request forgery (CSRF) protection issue that interfered with Varnish caching resolved." ( http://merch.docs.magento.com/ce/user_guide/Magento_Community_Edition_User_Guide.html#magento/release-notes-ce-1.9.2.html )

**Comment by miguelbalparda** [comment]
@m-overlund regarding your link, you should go to  system -> csrf -> add secret key to url (weird name) and disable CSRF. This is the fix Magento proposed for Varnish in the patch you are mentioning.
This is also worth checking https://github.com/deivisonarthur/Inovarti_FixAddToCartMage18

**Comment by miguelbalparda** [comment]
See also #846 @m-overlund @paales @Petce

**Comment by keyur-iksula** [comment]
I was facing an issue with custom checkout page where checkout returns empty cart page after refreshing page twice or thrice. I had gone through many post and found the solution that **default.vcl** code unset the session and cookie whenever any image or css not found on that page.

   if (true && req.url ~ ".*\.(?:css|js|jpe?g|png|gif|ico|swf)(?=\?|&|$)") {
       //unset req.http.Cookie;
       //unset req.http.X-Varnish-Faked-Session;
       return (lookup);
}

Hope it will help to someone.

**Comment by aricwatson** [comment]
>I had gone through many post and found the solution that default.vcl code unset the session and cookie whenever any image or css not found on that page.

I think you misunderstood the vcl - in this case it's unsetting the cookie and faked session header when the request ends in an asset suffix (css|js|jpe?g|png|gif|ico|swf) - i.e. if the request is for a css file, the cookie is unnecessary.

**Comment by Petce** [comment]
The real only way to fix this problem is to modify when Magento creates sessions.

Magento needs to only create a session when the customers state changes. I.e. Adding to the cart or submitting a form.

If someone was to modify Magento in that manner, it would no longer be needed for the Turpentine VCL to construct a fake session.

A solution like that would virtually solve every problem turpentine has because the number one issue with Varnish is session handling, or more accurately, that Varnish cannot initialise your web applications sessions (i.e. Magento).

Again, this problem gets significantly harder to deal with when the Magento store is running entirely under https secure.

**Comment by aricwatson** [comment]
Yes, that would certainly solve our formkey issues. However, Magento uses sessions for lots of things more than just formkey stuff - so such a change would need to take that into account. Not to mention third-party extensions!

**Comment by miguelbalparda** [comment]
This should be fixed in Turpentine 0.6.3, closing for now. There are several ways to fix this issue, see the documentation and #846 for more info. Feel free to reopen if the issue appears again.

**Comment by yannschepens** [comment]
Hi guys,

The commit relative to this problem, is not present into release-0.6.3 ... Is it normal ?

**Comment by jasonv77** [comment]
running magento 1.9.2.1 getting this add to cart issue, if i disable the csrf protections the issue goes away. I heard it is not recommended to disable this protection. any advice. 

im new to this , am not running turpentine or varnish as far as I know.

i tried a separate solution to fix this issue and got
this error when i tried to install inovarti fix.

There has been an error processing your request

Mage registry key "_singleton/fixaddtocartmage18/observer" already exists

Trace:
#0 /home/vasquezj/public_html/app/Mage.php(223): Mage::throwException('Mage registry k...')
#1 /home/vasquezj/public_html/app/Mage.php(477): Mage::register('_singleton/fixa...', false)
#2 /home/vasquezj/public_html/includes/src/__default.php(22054): Mage::getSingleton('fixaddtocartmag...')
#3 /home/vasquezj/public_html/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#4 /home/vasquezj/public_html/includes/src/__default.php(14405): Mage::dispatchEvent('controller_acti...', Array)
#5 /home/vasquezj/public_html/includes/src/__default.php(15028): Mage_Core_Controller_Varien_Action->postDispatch()
#6 /home/vasquezj/public_html/includes/src/__default.php(14276): Mage_Core_Controller_Front_Action->postDispatch()
#7 /home/vasquezj/public_html/includes/src/__default.php(18726): Mage_Core_Controller_Varien_Action->dispatch('index')
#8 /home/vasquezj/public_html/includes/src/__default.php(18256): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 /home/vasquezj/public_html/includes/src/__default.php(21084): Mage_Core_Controller_Varien_Front->dispatch()
#10 /home/vasquezj/public_html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#11 /home/vasquezj/public_html/index.php(83): Mage::run('', 'store')
#12 {main}

**Comment by miguelbalparda** [comment]
We have several fixes for this. You should try both the VCL fix and the Observer fix available under System - Configuration - Varnish Options - General

**Comment by jasonv77** [comment]
i dont have varnish options

**Comment by miguelbalparda** [comment]
Have you actually installed Nexcess_Turpentine?

**Comment by jasonv77** [comment]
no

**Comment by jasonv77** [comment]
and i am getting this error with a clean install of magento 1.9.2.1

**Comment by miguelbalparda** [comment]
@jasonv77 we can't help you in this case. I suggest you to install Nexcess_Turpentine and read the documentation first.

**Comment by jasonv77** [comment]
k

**Comment by AnuragKhandelwal15** [comment]
I had an issue after an upgrade from 1.8 to 1.9 that sometimes non-logged in users were unable to add product to cart but after applying https://github.com/deivisonarthur/Inovarti_FixAddToCartMage18, it seems working fine but not sure if other thing is going to break or not, till time great fix!!
keep helping!!

**Comment by aricwatson** [comment]
FYI, This should be essentially the same as the "use observer fix" option provided in the current Turpentine configuration. It does disable CRSF protection, which is why it isn't on by default.

**Comment by AnuragKhandelwal15** [comment]
@aricwatson I am newbie and dont know about turpentine discussed above, can you please tell me which to follow because I dont want to play with security in live site I am working on..
I didn't found turpentine extension in system>advanced but I have varnish installed.
Please suggest

**Comment by aricwatson** [comment]
The option is part of the [general options](https://github.com/nexcess/magento-turpentine/wiki/Configuration#general-options) in Turpentine.

What version of Turpentine are you using? I don't know of any add to cart issues since we instituted this fix back in August.

**Comment by AnuragKhandelwal15** [comment]
@aricwatson I am using magento 1.9.2.1 not turpentine

**Comment by punitgadhiya** [comment]
@Verguetz your extension working fine. Thanks 

https://github.com/deivisonarthur/Inovarti_FixAddToCartMage18/blob/master/README.md

**Comment by miguelbalparda** [comment]
@punitgadhiya this fix is already merged with Turpentine, if you try to install it again it might lead to unexpected results.
@AnuragKhandelwal15 Turpentine is not the same as Magento, thus the different version names.

**Comment by Krapulat** [comment]
@miguelbalparda It seems that with ajax add to cart, the problem appears. The cart is empty.

The links in category pages don't work:
<a onclick="setLocationAjax('https://www.example.com/checkout/cart/add/uenc/aHR0cHM6Ly93d3cudG9kb3VucGxhY2VyLmVzL3ZpYnJhZG9yZXMv/product/141/form_key/9yX0wizCRkXRSuIP/','141')"><i class="icon-basket"></i></a>

but if I click "add to cart" inside the product page, it works fine.

If I disable ajax add to cart, the problem doesn't appear. It works ok.

Do you know what can be the problem?

**Comment by Krapulat** [comment]
*Solved: I forgot to add "ajax" to the URL Blacklist.

**Comment by AnuragKhandelwal15** [comment]
@Krapulat : Can you elaborate the steps you followed?
It is because I have the same issue but somehow I am managing it by adding form_key using an observer mentioned above

**Comment by ADDISON74** [comment]
I am looking for a solution to disable the formkey checking for precisely actions (add to wishlist/compare/cart). Disabling CSRF in backend is not working. In this moment I edited a few core files to get this working (not many), but I need an elegant way. I made a request to Turpentine developers to take in consideration ideas from this page.

@EvrijnSD: how can be used your plugin? just copying the files on server? thank you.

**Comment by EvrijnSD** [comment]
Yes,

just copy the files,


2016-02-02 17:51 GMT+01:00 ADDISON <notifications@github.com>:

**Comment by ADDISON74** [comment]
I will do that. I appreciate for your work.

**Comment by ADDISON74** [comment]
@EvrijnSD : Your plugin is not working for comparison. There are still redirecting issues. You add a product in a category, then you go in other category and remove that product from side block. You will be redirected to previous page instead of staying on the same page. Same behavior for Clear All button in Compare side block. 

I updated the events to 1.9.2.2 but with no positive result. 

```php
'catalog_product_compare_add_product',
'catalog_product_compare_remove_product',
'catalog_product_compare_item_collection_clear'
```

I guess encoded URLs are still the big problem in this case. We should be able to disable this too.
