### ISSUE TITLE
Customers unable to login

### ISSUE THREAD

**Issue by evensisftw** [nexcess/magento-turpentine#477]
We've recently come across an issue in that customers don't seem to be able to login.

Certainly something to do with Varnish, as adding the /customer url to the url blacklist resolved the problem of not being able to log in.

This specifically seems to effects stores other than default, as our default UK site, was fine across the board when logging in without the above custom uri added to the blacklist.

**Comment by dam09fr** [comment]
We had a problem with customer cookies due to sub-domain's cookies.
If the customer go to http://mysite.com (varnish off) he gets redirected on www.mysite.com with "mysite.com" cookie set by PHP. Everything is fine but if at this moment we enable varnish, when he navigates to www.mysite.com, he gets a "www.mysite.com" cookie. The browser now have two cookies "mysite.com" and "www.mysite.com" and the customer cannot login to the website.

As a solution, we avoid sending http redirects from the root domain to the www subdomain by PHP : we redirect him from the loadbalancer directly (haproxy).

**Comment by miguelbalparda** [comment]
It seems #832 has a fix for this issue. would you mind giving it a try? It is on the devel branch until further testing.
