### ISSUE TITLE
How Do 2 Sets of VCL Files Interact?

### ISSUE THREAD

**Issue by sabonmichal** [nexcess/magento-turpentine#629]
Hi, I'm trying to understand how the built-in vcl files interact with the Turpentine vcl files or does Turpentine override the built-in ones? When I apply the Varnish Config from magento backend, it updates these files:

{{root_dir}}/var/default.vcl
{{root_dir}}/app/code/community/Nexcessnet/Turpentine/misc/version-3.vcl

but where is the override defined to bypass these files:?
/etc/default/varnish
/etc/varnish/default.vcl

Thank you :)

**Comment by aricwatson** [comment]
Turpentine will create a vcl and load it into varnish upon save. Depending on your varnish config, the /etc/varnish/default.vcl file may be loaded when Varnish starts up, requiring you to then load the vcl file generated by Turpentine - which is why it is recommended to symlink /etc/varnish/default.vcl to the turpentine generated vcl file.
https://github.com/nexcess/magento-turpentine/wiki/Configuration#servers
