### ISSUE TITLE
Turpentine is unable to recognize VCL file.

### ISSUE THREAD

**Issue by ahmedkbn** [nexcess/magento-turpentine#688]
Hi,

My setup is like below.

nginx (https) -> Varnish (6081) -> Apache (8083 https)

I am having issues with saving of the options in Turpentine by going into System -> Configuration ->Turpentine -> Varnish Options .

When i change some setting and save it even with wrong secret key, It just displays the message "The configuration has been saved." .I think it should print a error message if the secret key is wrong.

please help.

Thanks,
Ahmed

**Comment by aricwatson** [comment]
This sounds like some sort of a stack configuration issue, rather than a Turpentine issue. I'd suggest getting varnish/turp working well first before adding ngix to the mix.

I'll close the issue because this is a pretty old issue - however if you haven't yet found a solution feel free to reply and we'll help as much as possible.
