### ISSUE TITLE
What's the point in access=public caching?

### ISSUE THREAD

**Issue by jd-led** [nexcess/magento-turpentine#790]
I'm sure that there are certain reasons for access=public caching but generally isn't this what varnish is doing anyway?

- Page is requested from varnish
- Varnish gets page from cache
- ESI block are requested and put into page
- page is returned 

Ok, so if a page is requested that isn't in varnish's cache there will not be the overhead of generating the access=public ESI block. Is that the only benefit?

**Comment by ichalov** [comment]
It seems to be intended for blocks that are variable over time but should be the same in all pages, like news feed in sidebar. You need to make it ESI because otherwise it would show content that was actual at the time of caching and hence may show outdated version on some pages. And it's better not to make it private ESI because it would create a block copy for each user session and potentially over-flood cache storage.
