### ISSUE TITLE
NGINX+Varnish+Apache

### ISSUE THREAD

**Issue by magentoguru** [nexcess/magento-turpentine#809]
Hello, 
NGINX: 80/443
VARNISH: 8081
Apache: 8080

Here is the configuration:

1. NGINX:

upstream varnish {
    server 127.0.0.1:8081;
}
        
limit_req_zone $binary_remote_addr zone=one:10m rate=1r/s;

server {  
    listen       10*.1**.1**.**7:80 default;  
    server_name my.com www.my.com;

    location / { 
        proxy_read_timeout 300;	
        proxy_pass http://varnish;  
        proxy_set_header Host $http_host;  
        proxy_set_header X-Forwarded-Host $http_host;  
        proxy_set_header X-Real-IP $remote_addr;  
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  
        proxy_set_header HTTPS "";  
        proxy_hide_header X-Varnish;  
        proxy_hide_header Via; 
		add_header "X-UA-Compatible" "IE=Edge,chrome=1";
    }  
}  

server {  
    listen       443 ssl;  
    server_name my.com www.my.com;

    ssl                  on;  
    gzip                 on;
    gzip_min_length 1000;
	
    gzip_proxied    expired no-cache no-store private auth;
    gzip_types      text/plain application/xml text/css application/x-javascript;
    keepalive_timeout   70;
    ssl_protocols       TLSv1 TLSv1.1 TLSv1.2;
    #ssl_ciphers         AES128-SHA:AES256-SHA:RC4-SHA:DES-CBC3-SHA:RC4-MD5;
    ssl_certificate     /etc/ssl/private/my.nginx.crt;
    ssl_certificate_key /etc/ssl/private/my.nginx.crt;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;  

     

    location / {  
	    proxy_read_timeout 300;	 
        proxy_pass http://varnish;  
        proxy_set_header Host $http_host;  
        proxy_set_header X-Forwarded-Host $http_host;  
        proxy_set_header X-Real-IP $remote_addr;  
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  
        proxy_set_header HTTPS "on";  
        proxy_hide_header X-Varnish;  
        proxy_hide_header Via;  
    }  
	

2. Varnish:

/etc/default/varnish
     DAEMON_OPTS="-a :8081 \
             -T localhost:6082 \
             -f /etc/varnish/default.vcl \
             -S /etc/varnish/secret \
             -t 120 \
             -s malloc,256m"

/etc/varnish/default.vcl

backend default {
.host = "127.0.0.1";
.port = "8080";
} 

3. Apache:

etc/apache2/ports.conf

Listen 127.0.0.1:8080

/etc/apache2/sites-enabled/000-default.conf:

<VirtualHost 127.0.0.1:8080>
	ServerAdmin info@my.com
	ServerAlias my.com
	DocumentRoot /var/www/my/
	SetEnvIf HTTPS on HTTPS=on
	
	<IfModule mod_php5.c>
	    php_value display_errors on
	</IfModule>
	Options -Indexes
        <Directory /var/www/my>
            AllowOverride All
        </Directory>

</VirtualHost>

I still don't get my pages cached. Please help!

Thanks

**Comment by ichalov** [comment]
It looks strange in your setup that you manipulate HTTPS var itself. Have you tried passing this flag through Ssl-Offloaded like described in https://github.com/nexcess/magento-turpentine/wiki/SSL_Support ? 
I also believe there going to be problems with passing both HTTP and HTTPS traffic through the same varnish instance. It's more safe to attach https nginx to apache directly, bypassing varnish, and let only unencrypted pages to be cached.

**Comment by magentoguru** [comment]
Thanks for the good response. I have followed this tutorial (http://fbrnc.net/blog/2011/09/nginx-varnish-apache-magento-typo3). they implemented this sandwich type configuration.

**Comment by aricwatson** [comment]
I haven't used an nginx setup for this yet - but the other question I'd have is if you got turpentine and magneto working well first before adding the additional layer of nginx.

**Comment by magentoguru** [comment]
@aricwatson: i have never seen it working so far:(

**Comment by ichalov** [comment]
@magentoguru, The article you referenced is from 2011. That setup doesn't mention turpentine and it doesn't support ESI, so it would hardly be usable. 

The default magento setup produces 'Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0' header for most pages, varnish doesn't cache them due to this instruction. Even if you can find a way to override it, you would end up with excessive caching because there's no built in support for ESI in magento. 

Turpentine extension is supposed to fill that lack of ESI support, you need to install it to allow fine-grained caching between magento and varnish. It's better to start with varnish+apache configuration that works for unencrypted pages only and then proceed to add HTTPS support with nginx if needed (because HTTPS support is tricky to achieve). The generic installation instructions are here: https://github.com/nexcess/magento-turpentine/wiki/Installation .

**Comment by magentoguru** [comment]
Thank you very much  ichalov. i made changes in configuration. 

NGINX: 443
VARNISH: 80
Apache: 8080

and followed the instructions and got this response:



Accept-Ranges	bytes
Age	                        0
Cache-Control	       no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection	       keep-alive
Content-Encoding	gzip
Content-Length	12863
Content-Type	        text/html; charset=UTF-8
Date	                        Sat, 20 Jun 2015 09:14:34 GMT
Expires	                Thu, 19 Nov 1981 08:52:00 GMT
Pragma	                no-cache
Server	                Apache/2.4.7 (Ubuntu)
Set-Cookie	       frontend=elkbrn9cgnf9p32oa47rjn7td3; expires=Sat, 20-Jun-2015 10:14:34 GMT; Max-Age=3600; path=/; domain
=hipcycle.com
Vary	                      Accept-Encoding
Via	                    1.1 varnish
X-Varnish	            1147595636
x-powered-by	     PHP/5.5.9-1ubuntu4.5


seems like cache still not working?

Thanks

**Comment by magentoguru** [comment]
Thanks ichalov. it is fixed:).

but now i am not able to add products to checkout. though headers on that page are:
Accept-Ranges	bytes
Age	                        0
Cache-Control	        no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection	        keep-alive
Content-Encoding	gzip
Content-Length	9083
Content-Type	        text/html; charset=UTF-8
Date	                        Sat, 20 Jun 2015 09:52:54 GMT
Expires	                Thu, 19 Nov 1981 08:52:00 GMT
Pragma	                no-cache
Server	
Apache/2.4.7 (Ubuntu)
Set-Cookie              frontend=fis63bn8qg4h2ssd9i5rd1dp07; expires=Sat, 20-Jun-2015 10:52:54 GMT; Max-Age=3600; path=/; domain
=hipcycle.com
external_no_cache=1; expires=Sat, 20-Jun-2015 10:52:54 GMT; Max-Age=3600; path=/; domain=hipcycle.co
m                               Vary	
Accept-Encoding
Via	          1.1 varnish
X-Cache	MISS
X-Varnish	211221939
x-powered-by  PHP/5.5.9-1ubuntu4.5


Thank again.

**Comment by ichalov** [comment]
@magentoguru, I believe it's another issue, not related to the initial problem. There are many possible causes to inability to add a product to cart. Maybe you just forgot to flush all caches after making the last change, or the VCL file is not properly propagated to varnish, or it's third-party checkout extension incompatibility. You can find many different issues like this when searching for 'cart site:github.com/nexcess/magento-turpentine/' in google. I guess you'll need to learn from them by trying to find their causes in your setup in order to fix it.

**Comment by aricwatson** [comment]
Closing for lack of feedback.
