### ISSUE TITLE
Problem with session variables when using Varnish/Turpentine

### ISSUE THREAD

**Issue by scott82anderson** [nexcess/magento-turpentine#90]
Hi 

We have a Magento site where we have installed Varnish Cache 3.1.2 and Turpentine 0.5

Since the install the session variables no longer work which affects a Region setting ($_SESSION['location']) and also the Add to Cart functionality.

(See "Add to my Sales List" button here http://beta.missyconfidential.com.au/catalog/product/view/id/701/s/10-off-every-product-purchased-from-aria-argan-gold-moroccan-oil/category/16/)

Have we not installed the packages correctly or is there a configuration setting we're missing?

Thanks
Scott.

**Comment by xtremevision** [comment]
Hi,

We've experienced the same problem "Fatal error: Uncaught exception 'Mage_Core_Exception' with message 'Mage registry key "_singleton/customer/session" already exists' in /app/Mage.php:594", and just like @InsiderEdsHead the only thing that fixed it was disabling the module and clearing the cache.

In our case, we have a script /ajax/xx.php which we call up using ajax obviously, passing a single get parameter. In our case, the exception happens when the script tries to load a collection:

$section4 = Mage::getModel("catalog/product")->getCollection()
                                        ->setStoreID($store_id)
                                        ->addStoreFilter($store_id)
                                        ->addAttributeToSelect('*')
                                        ->addAttributeToFilter('status', array('eq' => 1))
                                        ->addAttributeToFilter('product_code', $product_code_id)
                                        ->addAttributeToFilter('plan_type', $plan_type_id)
                                        ->setOrder('price', 'desc');

Any ideas what it could and how it can be fixed?

Cheers,
Mike.

**Comment by xtremevision** [comment]
Hi,

Any ideas re our issues? Would telling Varnish to ignore a particular url or script fix it?

Cheers,
Michael.

**Comment by powerhousefitness** [comment]
This has happened to me and i found adding this to some of my scripts often solves it.

Mage::app();
// i add the line below after the Mage::app() call.
$session = Mage::getModel('core/session');

Hope this helps someone.
John
