### ISSUE TITLE
What is the most elegant way to put your website in maintenance mode?

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#925]
Just creating "maintenance.flag" file in your Magento root, maintenance mode won't be effective immediately. Personally before creating the file I stop Varnish service then I create the file with touch and start Varnish service.

Is this the best and fast way to put the website in maintenance mode?

**Comment by arosenhagen** [comment]
Since Varnish may cache your maintenance-page, we do the maintenance-check beforehand.
We have a setup like nginx:80 -> nginx:443 (ssl-offload) -> varnish:6081 -> nginx:8080 and do the check right at the beginning (nginx:80) directly via nginx. This way you do not have to restart varnish nor gets your maintenance-page cached at any time.
Furthermore we integrated a cookie-check to manually circumvent the maintenance-mode (as our developers do not have static IPs for proper whitelisting).
```
set $maintenance "off";
if (-f PATH_TO_DOCROOT/maintenance.flag) {
  set $maintenance "on";
}
if ($http_cookie ~ "SUPERSECRETCOOKIE=1") {
  set $maintenance "off";
}
if ($maintenance = "on") {
  return 503;
}
```
and for the folks: yes I know "if is evil"...

**Comment by craigcarnell** [comment]
https://github.com/nexcess/magento-turpentine/pull/885

**Comment by aricwatson** [comment]
These are a couple good options, and this isn't really a development issue, so I'm closing for now. But if you have another good option for this problem please don't hesitate to reply!
