### ISSUE TITLE
It will be great if we can have a few tutorials how to set up the polices

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#939]
There is a great info inside Wiki. Sometimes the things are not going well and we have to ask someone for help. I suggest creating a few tutorials explaining how you solve different tasks as a pro. For example setting up an ESI policy for a block or page, watching and investigating logs. This will help most of us who are asking sometimes basic things. If we get a common language I hope you can understand the issues much better.

Thank you.

**Comment by miguelbalparda** [comment]
Documentation/Wiki is not the only thing to check while using an open source project. Issues and PRs are an important part of the documentation too. 
This project is pretty old now and most of the scenarios where faced by one or more users and most (not to say 99%) have a solution either in the Wiki or in a PR/Issue. If the question is if we are going to make tutorials for developers not willing to read the documentation and check open and closed issues/PRs, the answer is that everything you need is already answered and if not, you can open an issue. We prefer to use the time we have to solve issues and create new features rather than creating tutorials to skip the documentation.

**Comment by ADDISON74** [comment]
Thank you for clarification.
