### ISSUE TITLE
 Message from VCC-compiler: Inline-C not allowed

### ISSUE THREAD

**Issue by specialtactics** [nexcess/magento-turpentine#948]
Hi there

When trying to save Varnish options, I get the following error:
```
    Failed to apply the VCL to 127.0.0.1:6082: Got unexpected response code from Varnish: 106 Message from VCC-compiler: Inline-C not allowed ('input' Line 2 Pos 1) C{ ## Running VCC-compiler failed, exited with 2 VCL compilation failed 
```

I am using CentOS 7 with Varnish 4 (all up to date)

**Comment by aricwatson** [comment]
Sounds like you need to make sure Varnish is starting up with the `-p vcc_allow_inline_c=on` parameter.

**Comment by elfeffe** [comment]
I have the same in Varnish 4, even with vcc_alllow_inline_c
I have to use Varnish 3

**Comment by ADDISON74** [comment]
is your VCL file starting with vcl 4 statement?

**Comment by specialtactics** [comment]
-p vcc_allow_inline_c=on is working for me now.

**Comment by ADDISON74** [comment]
In my case I set up a few moments ago a VM with Debian 8, Varnish 4 (from varnish repo), Magento 1.9.2.1/Magento sample 1.9/Turpentine master branch.

Even I am starting Varnish with the following parameters: 

-p vcc_allow_inline_c=on, and 
-p feature=+esi_ignore_other_elements

and I checked "ps aux | grep varnish" and it shows the parameters correctly, I cannot restart varnish after saving Turpentine configuration file in Magento backend. I get the following error message:

Message from VCC-compiler: 
Inline-C not allowed
('input' Line 2 Pos 1)
C{
##
Running VCC-compiler failed ...
VCL compilation failed

Keep digging ...

**Comment by ADDISON74** [comment]
I just added one more parameter which is not in your Wiki Installation for Varnish 4. 

-p cli_buffer=16384

Now everything is running as expected.

**Comment by ADDISON74** [comment]
Even you can Apply or Save configuration in Magento backend, if I want to restart varnish service from terminal I get the same error related to VCC-compiler "Inline-C not allowed ...

It is astonishing what is happening. This could be an issue into Varnish 4.0.3. To get back running Magento with Varnish, I have to start the service using the default varnish configuration file replacing all Turpentine added. 

Really how can Turpentine adding the configuration and make it running and I cannot restart Varnish 4 as root, using the same configuration file?

Keep digging ...

**Comment by ADDISON74** [comment]
Here comes a new issue even I can Apply or Save configuration in Magento backend, if I want to restart varnish service from terminal I get the same error related to VCC-compiler "Inline-C not allowed ...

It is astonishing what is happening. This could be an issue into Varnish 4.0.3 or Turpentine configuration. To get back running Magento with Varnish, I have to start the service using the default varnish configuration file replacing all Turpentine added before.

Really how can Turpentine adding the configuration and restarting the service and I cannot restart Varnish 4 as root, using the same configuration file?

Keep digging ...

**Comment by ADDISON74** [comment]
For sure when you apply a configuration file in backend Turpentine uses reload option. All the other options like start or restart will not work. 

Please stop your Varnish 4 service and start/restart it. You will get the error related to VCC-compiler.

If this comes from systemd I'll start to hate it!

**Comment by ADDISON74** [comment]
As I said pay attention to systemd configuration for those OS's which has it (Debian 8 in my case). Configuration of Varnish 4 with systemd at installation is not well done. I thought this issue is only for Debian repository, but now it is also for Varnish repo too.

After installing Varnish 4.0.3 do the following steps:

1) copy /lib/systemd/system/varnish.service to /etc/systemd/system/

2) edit /etc/systemd/system/varnish.service and comment line ExecStartPre (this causes the issue related to start/restart of this service with VCC-Compiler error)

3) Add the following parameters when Varnish service starts (line which starts with ExecStart=)
-p vcc_allow_inline_c=on
-p feature=+esi_ignore_other_elements
-p cli_buffer=16384 (for "Varnish data to write over length limit by ... characters"

4) execute "systemctl daemon-reload" because you change a systemd configuration file.

5) enable Varnish at boot "systemctl enable varnish.service".

6) execute "systemctl rebooot". Varnish should work normal. You can reload, restart, stop/start the service with no issues related to VCC-Compiler.

**Comment by miguelbalparda** [comment]
Any news on this one @specialtactics?

**Comment by specialtactics** [comment]
@miguelbalparda As I said in my last reply, it all works for me now.

**Comment by ADDISON74** [comment]
For those who want installing older versions of Varnish I suggest downloading the packages from official repository and install them in command line. By default if you want installing Varnish from repository automatically, you will get the latest version 4.1 which has some issues with ESI blocks and Age 0 header, especially in CentOS and 4.1.2 in Ubuntu. 

Here is the link for downloading the files you want. The sources are also there. I just installed 3.0.7 in CentOS 7 machine because version 4.1 created us a nightmare.

https://repo.varnish-cache.org/
