### ISSUE TITLE
Multi-store cookie

### ISSUE THREAD

**Issue by cscd98** [nexcess/magento-turpentine#97]
When changing store using the language switcher, a cookie would normally be created called store.

In the VCL this is in generate_session setting X-Varnish-Set-Cookie but on subsequent page clicks this information is lost. If there is a way to persist or re-send this information? That would the language selector would persist also. This is on the same URL (the menu content etc. does change)

X-Varnish-Set-Cookie    store=vax_ch_fr; expires=Thu, 13-Mar-2014 15:01:17 GMT; path=/; domain=vaxch.local; httponly

Would be possible as an alternative to persist a no-cache x-header? e.g.

If (req.http.Cookie ~ 'store') set some header to persist and handle that header in vcl_recv, vcl_fetch, vcl_deliver

Maybe I am misunderstanding the issue! I can deal with the store change on the first request, but on the second that information is lost because the code is never run again (because of a cached page for example). 

At least I think I can get it working, but I end up with ESI processing not enabled on various elements. Is there a way to just pass through varnish if certain GET variables are present? (and, on each subsequent page) because we have no way to record that. 

The cookie removal code is in generate_session, but it appears to do that more than once. Perhaps I could generate a real session when changing stores?

**Comment by Petce** [comment]
I want to add to this (May warrent a re-open).

In order to fix this issue, @aheadley added the following lines to the `vcl_recv` method

	if (req.http.Cookie ~ "\bcurrency=") {
	    set req.http.X-Varnish-Currency = regsub(
	        req.http.Cookie, ".*\bcurrency=([^;]*).*", "\1");
	}
	
	if (req.http.Cookie ~ "\bstore=") {
	    set req.http.X-Varnish-Store = regsub(
	        req.http.Cookie, ".*\bstore=([^;]*).*", "\1");
	}

And the following to the `vcl_hash` method

	if (req.http.X-Varnish-Store || req.http.X-Varnish-Currency) {
		# make sure data is for the right store and currency based on the *store*
		# and *currency* cookies
		hash_data("s=" + req.http.X-Varnish-Store + "&c=" + req.http.X-Varnish-Currency);
	}

This code says that if the currency cookie is set or the store cookie is set, set the values to the Unique Hash ID of the returned to-be-cached object.

While on the right track, it is still incomplete. Magento does not assign these cookies unless someone switches stores or currency. That is, if the homepage of the default store/currency is cached, but someone visits that page with the cookies set, Varnish will re-cache and create a new Hash because the cookies exist.

An easy fix to this is to tell the VCL file what the default values should be for given stores. Something like this at the top of the `vcl_recv` method:

	# Set the default Store View and Currency Code for the given domains
	set req.http.X-Default-Currency = "AUD";
	set req.http.X-Default-Store = "store_au_eng";
	if (req.http.host ~ "example\.com$") {
		set req.http.X-Default-Currency = "USD";
		set req.http.X-Default-Store = "store_usa_eng";
	}

Then we could further modify the earlier code in the `vcl_recv` to something like this:

        if (req.http.Cookie ~ "\bcurrency=") {
            set req.http.X-Varnish-Currency = regsub(
                req.http.Cookie, ".*\bcurrency=([^;]*).*", "\1");
        } else {
            set req.http.X-Varnish-Currency = req.http.X-Default-Currency;
        }
        
        if (req.http.Cookie ~ "\bstore=") {
            set req.http.X-Varnish-Store = regsub(
                req.http.Cookie, ".*\bstore=([^;]*).*", "\1");
        } else {
            set req.http.X-Varnish-Store = req.http.X-Default-Store;
        }

This modified code will now check to see if the cookies are set, if they are not, they will pull the default values for the determined store.

This approach is more robust and will produce more cache hits.

**Comment by miguelbalparda** [comment]
@Petce can you put this in a PR please?
