### ISSUE TITLE
Exclude Breadcrumbs from caching (so it shows the correct path on productpages)

### ISSUE THREAD

**Issue by rickbakker** [nexcess/magento-turpentine#988]
Hi guys,

Recently we discovered that the breadcrumbs are not showing correctly on the cached variant of one of our clients stores. On the uncached page the breadcrumbs show the path the customer follows to the product, but on the cached page it only shows the path that the first hit on that page was. In other words: It gets cached, and the breadcrumbs are not excluded from cache (hole punch?)

I've tried adding several things to the page.xml file like this:

    <reference name="breadcrumbs">
        <action method="setEsiOptions">
            <params>
                <access>private</access>
                <ttl>0</ttl>
                <method>ajax</method>
            </params>
        </action>
    </reference>

Also tried to add the <action> stuff in the code above to the <block>:

<block type="page/html_breadcrumbs" name="breadcrumbs" as="breadcrumbs">
        <action method="setEsiOptions">
            <params>
                <access>private</access>
                <ttl>0</ttl>
                <method>ajax</method>
            </params>
        </action>
</block>

This last piece of code breaks the breadcrumbs on the cached variant. It simply doesn't show the breadcrumbs at all then, but on the non cached variant, it shows them correctly.

I also tried changing the rendering of the block:

<?php echo $this->getChildHtml('breadcrumbs',false) ?>

The last 'false' should disable caching for that block, but it won't show the correct breadcrumbs just yet.

We are running Magento 1.8.1.0 and the latest version of Turpentine.

I've tried everything that i know of. Is there somebody that has working breadcrumbs on the productpages? Like i said; it now only shows the breadcrumbs that were active on the first hit to get the page cached. I need  to exclude the breadcrumbs from caching and maybe retrieve it via Ajax so it shows the correct path the customer went to get to the product. There should be something i'm overlooking or that i can learn here :)

**Comment by aricwatson** [comment]
@rickbakker sorry for the late reply!

Have you tried setting up your caching policies so that the breadcrumbs are *not* cached as part of any block? Then, they will be cached as part of the page cache, which will vary by URL and should prevent the problem of the breadcrumbs being cached from the first time the product appears.

As an example, look at a default 1.9x install (with Varnish/Turp) - a product such as the "Racer Back Maxi Dress" will appear with different breadcrumbs in both these URLs:

`/women/dresses-skirts/racer-back-maxi-dress-486.html` - navigated to via the 'Women' navigation item.

`/racer-back-maxi-dress-603.html` - navigated to via the 'Sale' navigation item.

**Comment by rickbakker** [comment]
Hi @aricwatson thanks for your reply! I was working on this issue today and i was googling again. I didnt notice your reply so sorry for that.

I have disabled the ESI rendering for the specific block:

        <reference name="breadcrumbs">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
					<disableEsiInjection>1</disableEsiInjection>
            		<method>ajax</method>
            		<ttl>0</ttl>
                    <dummy_blocks>
                        <header/>
                    </dummy_blocks>
                    <registry_keys>
                        <current_category/>
                        <current_product/>
                    </registry_keys>
                </params>
            </action>
        </reference>

This will make the breadcrumbs visible again, but unfortunately it does not show the correct path. Atleast not on this webshop i'm working on. The products all have the same URL. So if i navigate to a specific product via route 1, and then via route 2, it always shows the route 1 path, since that is the path that was first hit, so it is cached that way.

When i look at the webshop without Varnish, it is working correctly.

The only solution that i can think of is that in some way, the breadcrumbs have to be injected after the page is rendered, via ajax or jquery maybe. Maybe i can make some sort of PHP script that recognizes the path/route to the product and then spits out the correct code.

I figured out that the breadcrumbs don't work at all if you try to use the ESI rendering: then it will return blank. I have been on this issue for quite some time and tried even rendering ESI via Ajax but that is also blank. I think it's because of the script does not recognize the path because it's not recognizing the 'session' the visitor is in at the time of the page hit.

**Comment by aricwatson** [comment]
> All links to the products are like: domain.com/product_url.html even if you navigate via different categories.

Ah, yes that would do it unfortunately. 

> The only solution that i can think of is that in some way, the breadcrumbs have to be injected after the page is rendered, via ajax or jquery maybe. Maybe i can make some sort of PHP script that recognizes the path/route to the product and then spits out the correct code.

This, might work - just be sure to blacklist the ajax script's URL so that it doesn't get cached as well.

Another approach might be to disable ESI injection for the breadcrumb block as I'd originally suggested, but then set it's *parent* block to be cached with `<access>private</access>` - as a result that parent block would be cached per-user. This may not be the most efficient - but might turn out to be more efficient than using an ajax call to a script that has to be bootstrap the whole magento framework.

**Comment by rickbakker** [comment]
Hi @aricwatson, i agree, i would like to try this.

How can i accomplish this easily? Any suggestions? I'm pretty new to a Varnish/Turpentine configuration and i still have lots to learn :)

**Comment by aricwatson** [comment]
The specifics will depend on your theme's layout.xml - but basically, try to find if the breadcrumb block is contained within a parent block. Keep `<disableEsiInjection>1</disableEsiInjection>` on the breadcrumb block, then set up a new caching policy in your theme's local.xml for the breadcrumb parent block - perhaps like this:

    <reference name="[theparentblock]">
        <action method="setEsiOptions">
            <params>
                <access>private</access>
            </params>
        </action>
    </reference>

**Comment by rickbakker** [comment]
I think that i understand where you are going to with this, that is actually pretty smart. I will give that a try!

What i have to do is (if i understand you correctly):

- Disable caching on the breadcrumbs block.
- Create a new block, with a different name (breadcrumbscached maybe) and call the breadcrumbs from there. Enable private caching on this new block.

What we want to accomplish with this, is that the breadcrumbs get rendered without ESI, but since we are going to cache the parent new block, it will get cached eventually. And since it is a private session, every customer will get his own cached variant which should always show the correct path. Can we set the TTL to zero also? So that it won't get cached, but that it just shows the correct path every time?

Gonna give that a shot tomorrow. I will post the results here so everybody that is struggling with this i hope this works :)

**Comment by aricwatson** [comment]
> Create a new block, with a different name (breadcrumbscached maybe) and call the breadcrumbs from there. Enable private caching on this new block.

Actually, you may not need to create a new block - the breadcrumb block may already have a parent (often header or something like that, depends on theme) that you can apply the policy to.

**Comment by rickbakker** [comment]
I made a new block, and that all worked out fine, until i put this in the code:

        <reference name="wrapcrumbs">
        <action method="setEsiOptions">
            <params>
                <access>private</access>
            </params>
        </action>
        </reference>

(new block is wrapcrumbs) It gives the same results, just an empty breadcrumb. That's dissapointing...

**Comment by Pablo87x** [comment]
Hi everybody,
i have the same problem with breadcrumbs cache. Have you found the solution?

**Comment by rickbakker** [comment]
Still no solution to this problem unfortunately...

**Comment by connected** [comment]
+1 on this one. Same issue.

**Comment by aricwatson** [comment]
@rickbakker Do you see the ESI URL being inserted for the wrapcrumbs block? 

@connected Have you tried the fix I proposed above.

Are either of you seeing any errors in the logs (when you turn on debugging)?

**Comment by connected** [comment]
I think I've found the cause of the problem.

It seems that Magento breadcrumbs block uses last visited category value stored in session. This session value update happens on category page, not inside breadcrumbs block itself. 

Catalog page is cached by varnish, so this value update happens only once, when cache is empty and page is generated from backend server. 

Next time you access product from different access point (for example different category page) you will get incorrect breadcrumbs path because session value update wasn't triggered due to cached catalog page where this update supposed to happen.

**Comment by aricwatson** [comment]
That makes sense, and would explain what people are seeing. Some ideas (I can't really test these) - can you verify it doesn't work when set up as a private block, with using an Ajax method? Second idea - set the block to only cache if there's no text (`<only_cache_if>no_text</only_cache_if>`). Third idea - find the appropriate event and use `flush_event` to flush the breadcrumb block cache when a category is viewed.

**Comment by connected** [comment]
@aricwatson

This will not solve my problem because we have same product url for all products. For example:
Apple -> iPhone6 and Smartphones -> iPhone6. No matter from which category catalog you came from you will have url http://site.com/iphone6 (same as @rickbakker has on his site). I believe it has something to do with SEO. 

Url doesn't contain category info, so magento will use session value to get current category. This session value is set in catalog controller, and will be updated only when varish cache is empty. 

The only solution for my problem I see now is to create separate urls for each product path. For example Apple -> iPhone6 will have http://site.com/apple/iphone6, Smartphones -> iPhone6 http://site.com/smartphone/iphone6. This way each product path will be cached separately. As for SEO, we can include canonical(short) link in page head section. 

This is not Turpentine ext. fault, just something to keep in mind when dealing with varnish.

**Comment by rickbakker** [comment]
So there isn't a solution for the breadcrumbs to show correctly when you are using a single product page? I guess not. Maybe you can store the last path somewhere and show it that way, per visitor. But even when you do that, this will cause issues...

**Comment by aricwatson** [comment]
This (different breadcumbs while keeping one product URL) is something that will be difficult to implement in Turpentine - I'd suggest looking into implementing this in javascript, client-side rather than server-side.

**Comment by mabigo** [comment]
If someone is still interested in this issue. I managed to find a workaround. The idea is to set breadcrumbs as esi block with 0 ttl for product view handler, then grab the data from a helper instead of a block (because esi seem not to work well with _toHtml() and variables passed with assign()). Finally the helper method would grab the category out of referrer instead of lastViewedCategory. My current implementation is to dirty for a PR, so I am just giving an Idea.

**Comment by mabigo** [comment]
Here is a piece of code of how to getaway with completely cached category view and non existent LastVisitedCategoryId

`        $refererUrl = Mage::app()->getRequest()->getServer('HTTP_REFERER');
        
        $parsed_url = parse_url($refererUrl);
        
        // Trim slashes
        $path = trim($parsed_url['path'], '/');
        
        // Removed filter from category path
        if(strpos($path, '/')) {
        	$path = substr($path, 0, strpos($path, '/'));
        }
        
        $refererCategoryId = false;
        if ($this->_isUrlInternal($refererUrl)) {
        	$coreUrl = Mage::getModel('core/url_rewrite');
        	$coreUrl->setStoreId(Mage::app()->getStore()->getId());
        	$coreUrl->loadByRequestPath($path);
        	
        	$refererCategoryId = $coreUrl->getCategoryId();
        }`
